-- UNVERIFIED — reference only, not deployed by DCM (lives outside sources/definitions).
-- No live AWS credentials in this account to test this route. Replace the
-- REPLACE_* placeholders and move into sources/definitions/ once validated.

CREATE STORAGE INTEGRATION IF NOT EXISTS NERO_S3_INTEGRATION
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::123456789012:role/REPLACE_ROLE'
    STORAGE_ALLOWED_LOCATIONS = ('s3://REPLACE_BUCKET/nero/');

CREATE STAGE IF NOT EXISTS NERO_DB."00_BRONZE".S3_STAGE
    URL = 's3://REPLACE_BUCKET/nero/'
    STORAGE_INTEGRATION = NERO_S3_INTEGRATION
    FILE_FORMAT = NERO_DB."00_BRONZE".JSON_LINES;

CREATE PIPE IF NOT EXISTS NERO_DB."00_BRONZE".CONTRACT_PIPE
    AUTO_INGEST = TRUE
AS
COPY INTO NERO_DB."00_BRONZE".RAW_ENVELOPES
    (PAYLOAD, FILE_NAME, FILE_ROW_NUMBER, FILE_CONTENT_KEY, INGESTED_AT)
FROM (
    SELECT
        TO_JSON($1), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$START_SCAN_TIME
    FROM @NERO_DB."00_BRONZE".S3_STAGE
)
FILE_FORMAT = (FORMAT_NAME = NERO_DB."00_BRONZE".JSON_LINES)
PATTERN = '.*[.]jsonl'
ON_ERROR = 'SKIP_FILE';
