-- =============================================================================
-- Data Contract Ingestion Engine -- RETIRED.
--
-- This file used to hand-write the whole contract-validation control plane:
-- CONTROL_DATA_CONTRACTS, CONTROL_RUN_AUDIT, CONTROL_RELEASE_POINTER,
-- CONTROL_INGEST_WATERMARKS, CONTRACT_GATE_TASK, and PROCESS_BATCH/
-- RUN_PENDING -- a Python stored procedure that parsed a JSON envelope,
-- checked it field-by-field against the pinned contract, and only then
-- published into VALIDATED_<DATASET> (full DELETE+reload, or MERGE for
-- incremental datasets).
--
-- All of that is now dbt: analytics/models/silver/validated_<dataset>.sql
-- read directly from the typed BRONZE_<DATASET> tables and filter by the
-- same contract rules in plain SQL (nullability, enums, FKs, the
-- redeem/reward_id policy), with dbt tests (analytics/models/silver/
-- silver.yml) as the regression safety net. validated_transactions is
-- dbt's native `materialized='incremental'` -- the same MERGE-by-primary-
-- key behavior PROCESS_BATCH used to hand-implement for that one dataset.
--
-- Traded away by this move, on purpose: PROCESS_BATCH's atomic batch-level
-- gating (a bad batch never touched VALIDATED_* at all) and its audit
-- trail (PUBLISHED/REJECTED/INCOMPLETE/SUPERSEDED per batch_id). dbt's
-- model runs and its own tests instead -- a failing test surfaces after
-- the model has already materialized, visible via `dbt build`'s exit code
-- and DBT_DAILY_REFRESH_TASK's run history, not a bespoke audit table.
--
-- The ingestion adapters (ingestion/load_csv_batch.py, GENERATE_SYNTHETIC_
-- DAY(), INGEST_FROM_GOOGLE_SHEETS()) are unchanged in what they do --
-- land typed rows into bronze -- they just no longer call PROCESS_BATCH
-- at the end, since it no longer exists.
-- =============================================================================
