-- =============================================================================
-- GENERATED by ingestion/build.py from ingestion/contract/ — do not hand-edit.
-- Pipeline stage/dependency documentation. Rows loaded by
-- `python ingestion/build.py --seed`, not by DCM (schema only here).
-- =============================================================================

DEFINE TABLE NERO_DB."03_LINEAGE".PIPELINE_STAGE_MAP (
    DATABASE_NAME    VARCHAR(200)  NOT NULL,
    SCHEMA_NAME      VARCHAR(200)  NOT NULL,
    OBJECT_NAME      VARCHAR(200)  NOT NULL,
    STAGE            VARCHAR(50)   NOT NULL,
    UPSTREAM_OBJECT  VARCHAR(400),
    DESCRIPTION      VARCHAR(1000),
    PRIMARY KEY (DATABASE_NAME, SCHEMA_NAME, OBJECT_NAME)
)
COMMENT = 'Human-readable pipeline lineage: which object feeds which. Not a substitute for Snowflake ACCESS_HISTORY/OBJECT_DEPENDENCIES or dbt''s own manifest.json (both trace real object-level dependencies automatically) — this is documentation-as-data for people browsing the schema, kept in sync by ingestion/build.py --seed.';
