-- =============================================================================
-- GENERATED by ingestion/build.py from ingestion/contract/ — do not hand-edit.
-- PII column registry. Rows loaded by `python ingestion/build.py --seed`
-- from the contract's pii/pii_kind tags (schema only here).
-- =============================================================================

DEFINE TABLE NERO_DB."05_PII_CONTROL".PII_COLUMN_REGISTRY (
    TABLE_NAME            VARCHAR(200)  NOT NULL,
    COLUMN_NAME           VARCHAR(200)  NOT NULL,
    DATASET_NAME          VARCHAR(200)  NOT NULL,
    PII_KIND              VARCHAR(100)  NOT NULL,
    MASKING_POLICY_NAME   VARCHAR(400),
    MASKING_ENFORCED      BOOLEAN       NOT NULL,
    LOADED_AT             TIMESTAMP_TZ  DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TABLE_NAME, COLUMN_NAME)
)
COMMENT = 'Governance registry of every column tagged pii:true in the contract. MASKING_ENFORCED is FALSE for all rows on this account: its Snowflake edition does not support masking policies at all (confirmed directly — see ingestion/reference/masking.sql). This table records governance intent even where enforcement is not live.';
