-- =============================================================================
-- GENERATED by ingestion/build.py from ingestion/contract/ — do not hand-edit.
-- One VALIDATED_<DATASET> table per contract dataset, columns/types derived
-- directly from the contract so schema drift between the two is impossible.
-- =============================================================================

DEFINE TABLE NERO_DB.NERO_LOYALTY.VALIDATED_LOYALTY_CUSTOMERS (
    CUSTOMER_ID          NUMBER NOT NULL,
    SIGNUP_DATE          DATE NOT NULL,
    TIER                 VARCHAR(16777216) NOT NULL,
    HOME_STORE_ID        NUMBER,
    BATCH_ID             VARCHAR(200) NOT NULL,
    PRIMARY KEY (CUSTOMER_ID)
)
COMMENT = 'Validated loyalty_customers dataset, current release only. Generated from contract v3.';

DEFINE TABLE NERO_DB.NERO_LOYALTY.VALIDATED_LOYALTY_EVENTS (
    EVENT_ID             NUMBER NOT NULL,
    CUSTOMER_ID          NUMBER NOT NULL,
    EVENT_TS             TIMESTAMP_TZ NOT NULL,
    EVENT_TYPE           VARCHAR(16777216) NOT NULL,
    REWARD_ID            NUMBER,
    STORE_ID             NUMBER,
    BATCH_ID             VARCHAR(200) NOT NULL,
    PRIMARY KEY (EVENT_ID)
)
COMMENT = 'Validated loyalty_events dataset, current release only. Generated from contract v3.';

DEFINE TABLE NERO_DB.NERO_LOYALTY.VALIDATED_STORES (
    STORE_ID             NUMBER NOT NULL,
    STORE_NAME           VARCHAR(200) NOT NULL,
    REGION               VARCHAR(100) NOT NULL,
    FORMAT               VARCHAR(16777216) NOT NULL,
    OPENED_DATE          DATE NOT NULL,
    BATCH_ID             VARCHAR(200) NOT NULL,
    PRIMARY KEY (STORE_ID)
)
COMMENT = 'Validated stores dataset, current release only. Generated from contract v3.';

DEFINE TABLE NERO_DB.NERO_LOYALTY.VALIDATED_TRANSACTIONS (
    TRANSACTION_ID       NUMBER NOT NULL,
    STORE_ID             NUMBER NOT NULL,
    TRANSACTION_TS       TIMESTAMP_TZ NOT NULL,
    CUSTOMER_ID          NUMBER,
    BASKET_TOTAL         NUMBER(8,2) NOT NULL,
    ITEM_COUNT           NUMBER NOT NULL,
    PAYMENT_TYPE         VARCHAR(16777216) NOT NULL,
    BATCH_ID             VARCHAR(200) NOT NULL,
    PRIMARY KEY (TRANSACTION_ID)
)
COMMENT = 'Validated transactions dataset, current release only. Generated from contract v3.';

DEFINE VIEW NERO_DB.NERO_LOYALTY.REPORTING_CURRENT_RELEASE AS
SELECT
    p.CURRENT_BATCH_ID,
    p.CURRENT_RELEASE_AT,
    (SELECT COUNT(*) FROM NERO_DB.NERO_LOYALTY.VALIDATED_LOYALTY_CUSTOMERS) AS LOYALTY_CUSTOMERS_COUNT,
    (SELECT COUNT(*) FROM NERO_DB.NERO_LOYALTY.VALIDATED_LOYALTY_EVENTS) AS LOYALTY_EVENTS_COUNT,
    (SELECT COUNT(*) FROM NERO_DB.NERO_LOYALTY.VALIDATED_STORES) AS STORES_COUNT,
    (SELECT COUNT(*) FROM NERO_DB.NERO_LOYALTY.VALIDATED_TRANSACTIONS) AS TRANSACTIONS_COUNT
FROM NERO_DB.NERO_LOYALTY.CONTROL_RELEASE_POINTER p
WHERE p.POINTER_NAME = 'LOYALTY_SNAPSHOT';
