#!/usr/bin/env python3
"""Generator: ingestion/contract.yaml -> generated DCM SQL + reference SQL,
and (with --seed) loads the contract into CONTROL_DATA_CONTRACTS.

Reads the single unified contract (business rules + ingestion strategy +
PII tags) and emits:
  - sources/definitions/ingestion/raw.sql       (DCM-managed, deployed)
  - sources/definitions/ingestion/validated.sql (DCM-managed, deployed)
  - ingestion/reference/s3.sql       (NOT under sources/definitions, so DCM
    ignores it — real SQL, but UNVERIFIED: no live AWS credentials here)
  - ingestion/reference/masking.sql  (real SQL for PII masking + the
    column-attach step, also UNVERIFIED: this Snowflake account's edition
    doesn't support masking policies at all, confirmed independent of DCM)

Only ingestion.source.type=internal_stage + ingestion.landing.type=native is
deployed and tested end-to-end. Rejects unknown keys at every level so a typo
in the contract fails the build instead of silently doing nothing.

Usage:
    python ingestion/build.py                              # generate only
    python ingestion/build.py --seed -c <snow_connection>   # generate + seed
"""
import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CONTRACT_PATH = ROOT / "ingestion" / "contract.yaml"
DB_SCHEMA = "NERO_DB.NERO_LOYALTY"

SQL_TYPE_MAP = {
    "integer": "NUMBER",
    "decimal": None,  # needs precision/scale, handled specially
    "string": None,   # needs max_length, handled specially
    "date": "DATE",
    "timestamp_tz": "TIMESTAMP_TZ",
}

ALLOWED = {
    "top": {"version", "contract_id", "wire_format", "ingestion", "freshness", "datasets"},
    "ingestion": {"source", "landing"},
    "source": {"type", "file_pattern", "on_error", "internal_stage", "s3"},
    "landing": {"type", "table_name", "iceberg"},
    "dataset": {"primary_key", "owners", "columns", "policies"},
    "column": {"type", "nullable", "max_length", "enum", "foreign_key", "precision", "scale",
               "pii", "pii_kind", "example"},
    "foreign_key": {"dataset", "column"},
    "policy": {"kind", "column", "when"},
}


def _check_keys(d, allowed_key, path):
    unknown = set(d.keys()) - ALLOWED[allowed_key]
    if unknown:
        sys.exit(f"build.py: unknown key(s) {sorted(unknown)} at {path} — refusing to build")


def sql_column_type(name, spec, path):
    t = spec["type"]
    if t == "string":
        max_len = spec.get("max_length", 16777216)
        return f"VARCHAR({max_len})"
    if t == "decimal":
        precision = spec.get("precision", 38)
        scale = spec.get("scale", 0)
        return f"NUMBER({precision},{scale})"
    if t in SQL_TYPE_MAP:
        return SQL_TYPE_MAP[t]
    sys.exit(f"build.py: unsupported column type '{t}' at {path}")


def load_contract():
    raw_bytes = CONTRACT_PATH.read_bytes()
    contract_hash = hashlib.sha256(raw_bytes).hexdigest()
    doc = yaml.safe_load(raw_bytes)

    _check_keys(doc, "top", "top level")
    _check_keys(doc["ingestion"], "ingestion", "ingestion")
    _check_keys(doc["ingestion"]["source"], "source", "ingestion.source")
    _check_keys(doc["ingestion"]["landing"], "landing", "ingestion.landing")
    for ds_name, ds in doc["datasets"].items():
        _check_keys(ds, "dataset", f"datasets.{ds_name}")
        for col_name, col in ds["columns"].items():
            _check_keys(col, "column", f"datasets.{ds_name}.columns.{col_name}")
            if "foreign_key" in col:
                _check_keys(col["foreign_key"], "foreign_key", f"datasets.{ds_name}.columns.{col_name}.foreign_key")
        for policy in ds.get("policies", []):
            _check_keys(policy, "policy", f"datasets.{ds_name}.policies")

    return doc, raw_bytes, contract_hash


def gen_raw_landing(doc):
    landing = doc["ingestion"]["landing"]
    source = doc["ingestion"]["source"]
    lines = [
        "-- =============================================================================",
        "-- GENERATED by ingestion/build.py from ingestion/contract.yaml — do not hand-edit.",
        "-- Edit the contract and rerun `python ingestion/build.py` instead.",
        "-- =============================================================================",
        "",
        f"DEFINE FILE FORMAT {DB_SCHEMA}.JSON_LINES",
        "    TYPE = JSON",
        "    STRIP_OUTER_ARRAY = FALSE",
        "    COMMENT = 'One JSON object per line (manifest or record envelope).';",
        "",
    ]
    if source["type"] == "internal_stage":
        lines += [
            f"DEFINE STAGE {DB_SCHEMA}.LANDING_STAGE",
            f"    FILE_FORMAT = {DB_SCHEMA}.JSON_LINES",
            "    COMMENT = 'Credential-free internal stage for manual/CI batch uploads.';",
            "",
        ]
    else:
        sys.exit(f"build.py: source.type '{source['type']}' has no deployed definition here — "
                  f"see ingestion/reference/s3.sql for the (unverified) s3 route.")

    if landing["type"] == "native":
        lines += [
            f"DEFINE TABLE {landing['table_name']} (",
            "    PAYLOAD          VARCHAR       NOT NULL,",
            "    FILE_NAME        VARCHAR,",
            "    FILE_ROW_NUMBER  NUMBER,",
            "    FILE_CONTENT_KEY VARCHAR,",
            "    INGESTED_AT      TIMESTAMP_TZ  DEFAULT CURRENT_TIMESTAMP()",
            ")",
            "COMMENT = 'Raw landing table. One row per JSON line loaded from LANDING_STAGE via COPY INTO. Batches are identified by FILE_NAME.';",
        ]
    elif landing["type"] == "iceberg":
        iceberg = landing["iceberg"]
        lines += [
            f"DEFINE ICEBERG TABLE {landing['table_name']} (",
            "    PAYLOAD          VARCHAR       NOT NULL,",
            "    FILE_NAME        VARCHAR,",
            "    FILE_ROW_NUMBER  NUMBER,",
            "    FILE_CONTENT_KEY VARCHAR,",
            "    INGESTED_AT      TIMESTAMP_TZ",
            ")",
            f"CATALOG = 'SNOWFLAKE'",
            f"EXTERNAL_VOLUME = '{iceberg['external_volume']}'",
            f"BASE_LOCATION = '{iceberg['base_location']}';",
        ]
    else:
        sys.exit(f"build.py: unknown landing.type '{landing['type']}'")

    return "\n".join(lines) + "\n"


def gen_validated_tables(doc):
    lines = [
        "-- =============================================================================",
        "-- GENERATED by ingestion/build.py from ingestion/contract.yaml — do not hand-edit.",
        "-- One VALIDATED_<DATASET> table per contract dataset, columns/types derived",
        "-- directly from the contract so schema drift between the two is impossible.",
        "-- =============================================================================",
        "",
    ]
    for ds_name, ds in doc["datasets"].items():
        table = f"{DB_SCHEMA}.VALIDATED_{ds_name.upper()}"
        col_lines = []
        for col_name, col in ds["columns"].items():
            sql_type = sql_column_type(col_name, col, f"datasets.{ds_name}.columns.{col_name}")
            not_null = "" if col.get("nullable", True) else " NOT NULL"
            col_lines.append(f"    {col_name.upper():<20} {sql_type}{not_null},")
        col_lines.append("    BATCH_ID             VARCHAR(200) NOT NULL,")
        pk_cols = ", ".join(c.upper() for c in ds["primary_key"])
        col_lines.append(f"    PRIMARY KEY ({pk_cols})")
        lines.append(f"DEFINE TABLE {table} (")
        lines += col_lines
        lines.append(")")
        version = doc["version"]
        lines.append(f"COMMENT = 'Validated {ds_name} dataset, current release only. Generated from contract v{version}.';")
        lines.append("")
    lines.append(f"DEFINE VIEW {DB_SCHEMA}.REPORTING_CURRENT_RELEASE AS")
    lines.append("SELECT")
    lines.append("    p.CURRENT_BATCH_ID,")
    lines.append("    p.CURRENT_RELEASE_AT,")
    counts = ",\n".join(
        f"    (SELECT COUNT(*) FROM {DB_SCHEMA}.VALIDATED_{ds_name.upper()}) AS {ds_name.upper()}_COUNT"
        for ds_name in doc["datasets"]
    )
    lines.append(counts)
    lines.append(f"FROM {DB_SCHEMA}.CONTROL_RELEASE_POINTER p")
    lines.append("WHERE p.POINTER_NAME = 'LOYALTY_SNAPSHOT';")
    return "\n".join(lines) + "\n"


def gen_masking_reference(doc):
    """One reference file: policy definitions + the column-attach step. Both
    UNVERIFIED on this account (masking policies aren't supported by its
    edition at all — confirmed directly, independent of DCM), and DCM doesn't
    yet support attaching a policy to a column even where it is supported."""
    pii_cols = []  # (dataset, column, sql_type, pii_kind)
    for ds_name, ds in doc["datasets"].items():
        for col_name, col in ds["columns"].items():
            if col.get("pii"):
                pii_cols.append((ds_name, col_name, col["type"], col.get("pii_kind", "identifier")))

    if not pii_cols:
        return None

    pii_types = sorted({(t, k) for _, _, t, k in pii_cols})
    lines = [
        "-- UNVERIFIED — reference only, not deployed by DCM (lives outside sources/definitions).",
        "-- This Snowflake account's edition does not support masking policies at all —",
        "-- confirmed directly: `CREATE MASKING POLICY ...` errors with",
        "-- \"Unsupported feature 'MASKING POLICY'\" independent of DCM. This SQL is",
        "-- correct standard syntax; move the DEFINE block into sources/definitions/",
        "-- once run on an edition that supports masking policies (Enterprise+).",
        "--",
        "-- The ALTER TABLE block below is a further MANUAL step even then: DCM's",
        "-- DEFINE MASKING POLICY only creates the policy, not attaching it to a",
        "-- column — that isn't a supported DCM primitive yet.",
        "",
        "-- ---- policy definitions ----",
        "",
    ]
    for sql_type, pii_kind in pii_types:
        policy_name = f"{DB_SCHEMA}.MASK_{pii_kind.upper()}_{sql_type.upper()}"
        col_type = "NUMBER" if sql_type == "integer" else "VARCHAR"
        lines += [
            f"DEFINE MASKING POLICY {policy_name} AS (val {col_type}) RETURNS {col_type} ->",
            "    CASE",
            "        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN val",
            "        ELSE NULL",
            "    END",
            f"COMMENT = 'Masks {pii_kind} columns of type {sql_type} for any role other than ACCOUNTADMIN.';",
            "",
        ]

    lines.append("-- ---- attach to columns (manual, after the policies above are deployed) ----")
    lines.append("")
    for ds_name, col_name, sql_type, pii_kind in pii_cols:
        table = f"{DB_SCHEMA}.VALIDATED_{ds_name.upper()}"
        policy = f"{DB_SCHEMA}.MASK_{pii_kind.upper()}_{sql_type.upper()}"
        lines.append(f"ALTER TABLE {table} MODIFY COLUMN {col_name.upper()} SET MASKING POLICY {policy};")

    return "\n".join(lines) + "\n"


def gen_s3_reference(doc):
    s3 = doc["ingestion"]["source"]["s3"]
    landing = doc["ingestion"]["landing"]
    lines = [
        "-- UNVERIFIED — reference only, not deployed by DCM (lives outside sources/definitions).",
        "-- No live AWS credentials in this account to test this route. Replace the",
        "-- REPLACE_* placeholders and move into sources/definitions/ once validated.",
        "",
        f"CREATE STORAGE INTEGRATION IF NOT EXISTS {s3['integration_name']}",
        "    TYPE = EXTERNAL_STAGE",
        "    STORAGE_PROVIDER = 'S3'",
        "    ENABLED = TRUE",
        f"    STORAGE_AWS_ROLE_ARN = '{s3['aws_role_arn']}'",
        f"    STORAGE_ALLOWED_LOCATIONS = ('{s3['bucket_url']}');",
        "",
        f"CREATE STAGE IF NOT EXISTS {s3['stage_name']}",
        f"    URL = '{s3['bucket_url']}'",
        f"    STORAGE_INTEGRATION = {s3['integration_name']}",
        f"    FILE_FORMAT = {DB_SCHEMA}.JSON_LINES;",
    ]
    if s3.get("auto_ingest"):
        lines += [
            "",
            f"CREATE PIPE IF NOT EXISTS {s3['pipe_name']}",
            "    AUTO_INGEST = TRUE",
            "AS",
            f"COPY INTO {landing['table_name']}",
            "    (PAYLOAD, FILE_NAME, FILE_ROW_NUMBER, FILE_CONTENT_KEY, INGESTED_AT)",
            "FROM (",
            "    SELECT",
            "        TO_JSON($1), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,",
            "        METADATA$FILE_CONTENT_KEY, METADATA$START_SCAN_TIME",
            f"    FROM @{s3['stage_name']}",
            ")",
            f"FILE_FORMAT = (FORMAT_NAME = {DB_SCHEMA}.JSON_LINES)",
            f"PATTERN = '{doc['ingestion']['source']['file_pattern']}'",
            "ON_ERROR = 'SKIP_FILE';",
        ]
    return "\n".join(lines) + "\n"


def seed(connection, doc, raw_bytes, contract_hash):
    """Loads the contract into CONTROL_DATA_CONTRACTS (data-plane, outside
    DCM's schema-only scope). Additive: an existing contract_id+version is
    left alone, so bumping `version` in the YAML is how you publish a change."""
    contract_json_text = json.dumps(doc)
    sql = f"""
    INSERT INTO NERO_DB.NERO_LOYALTY.CONTROL_DATA_CONTRACTS (CONTRACT_ID, VERSION, CONTRACT_JSON, CONTRACT_HASH)
    SELECT '{doc["contract_id"]}', {doc["version"]}, PARSE_JSON($${contract_json_text}$$), '{contract_hash}'
    WHERE NOT EXISTS (
        SELECT 1 FROM NERO_DB.NERO_LOYALTY.CONTROL_DATA_CONTRACTS
        WHERE CONTRACT_ID = '{doc["contract_id"]}' AND VERSION = {doc["version"]}
    );
    """
    subprocess.run(["snow", "sql", "-c", connection, "-q", sql], check=True)
    print(f"Seeded {doc['contract_id']} v{doc['version']}, hash={contract_hash}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", action="store_true", help="also load the contract into CONTROL_DATA_CONTRACTS")
    parser.add_argument("-c", "--connection", help="snow CLI connection name (required with --seed)")
    args = parser.parse_args()
    if args.seed and not args.connection:
        sys.exit("build.py: --seed requires -c/--connection")

    doc, raw_bytes, contract_hash = load_contract()

    definitions_dir = ROOT / "sources" / "definitions" / "ingestion"
    reference_dir = ROOT / "ingestion" / "reference"
    definitions_dir.mkdir(parents=True, exist_ok=True)
    reference_dir.mkdir(parents=True, exist_ok=True)

    (definitions_dir / "raw.sql").write_text(gen_raw_landing(doc))
    (definitions_dir / "validated.sql").write_text(gen_validated_tables(doc))

    masking_sql = gen_masking_reference(doc)
    masking_path = reference_dir / "masking.sql"
    if masking_sql:
        masking_path.write_text(masking_sql)
    elif masking_path.exists():
        masking_path.unlink()

    (reference_dir / "s3.sql").write_text(gen_s3_reference(doc))

    print(f"Built from {CONTRACT_PATH.relative_to(ROOT)} (contract v{doc['version']}, hash={contract_hash})")
    print("Generated (DCM-managed, deployed):")
    print("  sources/definitions/ingestion/raw.sql")
    print("  sources/definitions/ingestion/validated.sql")
    print("Generated (reference only, NOT deployed by DCM):")
    print("  ingestion/reference/s3.sql (unverified — no live AWS credentials)")
    if masking_sql:
        print("  ingestion/reference/masking.sql (unverified — account edition lacks masking policy support)")

    if args.seed:
        seed(args.connection, doc, raw_bytes, contract_hash)


if __name__ == "__main__":
    main()
