#!/usr/bin/env python3
"""Generator: ingestion/contract/ (meta.yaml + datasets/*.yaml) -> generated
DCM SQL + reference SQL, and (with --seed) loads the contract, the PII
column registry, and the lineage map with data.

NERO_DB is split into numbered schemas by pipeline stage:
  00_BRONZE       raw landing (RAW_ENVELOPES, LANDING_STAGE, JSON_LINES)
  01_SILVER       contract-validated tables (VALIDATED_*)
  02_CONTROL      contract registry, audit, release pointer, work table,
                  gate task, PROCESS_BATCH/RUN_PENDING (see engine.sql,
                  hand-written, not generated by this script)
  03_LINEAGE      pipeline stage/dependency documentation
  04_METADATA     ingestion freshness/reporting (current release + counts)
  05_PII_CONTROL  PII column registry, sourced from the contract's pii tags

Emits:
  - sources/definitions/ingestion/raw.sql        (DCM-managed, deployed)
  - sources/definitions/ingestion/validated.sql  (DCM-managed, deployed)
  - sources/definitions/ingestion/lineage.sql     (DCM-managed, deployed —
    schema only; rows loaded by --seed, since DCM manages schema not data)
  - sources/definitions/ingestion/pii_registry.sql (DCM-managed, deployed —
    schema only; rows loaded by --seed)
  - ingestion/reference/s3.sql       (NOT under sources/definitions, so DCM
    ignores it — real SQL, but UNVERIFIED: no live AWS credentials here)
  - ingestion/reference/masking.sql  (real SQL for PII masking + the
    column-attach step, also UNVERIFIED: this Snowflake account's edition
    doesn't support masking policies at all, confirmed independent of DCM)

Only ingestion.source.type=internal_stage + ingestion.landing.type=native is
deployed and tested end-to-end. Rejects unknown keys at every level so a typo
in the contract fails the build instead of silently doing nothing.

Usage:
    python ingestion/build.py                              # generate only
    python ingestion/build.py --seed -c <snow_connection>   # generate + seed
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path

from contract_loader import load_contract

ROOT = Path(__file__).resolve().parent.parent

BRONZE = 'NERO_DB."00_BRONZE"'
SILVER = 'NERO_DB."01_SILVER"'
CONTROL = 'NERO_DB."02_CONTROL"'
LINEAGE = 'NERO_DB."03_LINEAGE"'
METADATA = 'NERO_DB."04_METADATA"'
PII_CONTROL = 'NERO_DB."05_PII_CONTROL"'

SQL_TYPE_MAP = {
    "integer": "NUMBER",
    "decimal": None,  # needs precision/scale, handled specially
    "string": None,   # needs max_length, handled specially
    "date": "DATE",
    "timestamp_tz": "TIMESTAMP_TZ",
}


def sql_column_type(name, spec, path):
    t = spec["type"]
    if t == "string":
        max_len = spec.get("max_length", 16777216)
        return f"VARCHAR({max_len})"
    if t == "decimal":
        precision = spec.get("precision", 38)
        scale = spec.get("scale", 0)
        return f"NUMBER({precision},{scale})"
    if t in SQL_TYPE_MAP:
        return SQL_TYPE_MAP[t]
    sys.exit(f"build.py: unsupported column type '{t}' at {path}")


def gen_raw_landing(doc):
    landing = doc["ingestion"]["landing"]
    source = doc["ingestion"]["source"]
    lines = [
        "-- =============================================================================",
        "-- GENERATED by ingestion/build.py from ingestion/contract/ — do not hand-edit.",
        "-- Edit the contract and rerun `python ingestion/build.py` instead.",
        "-- =============================================================================",
        "",
        f"DEFINE FILE FORMAT {BRONZE}.JSON_LINES",
        "    TYPE = JSON",
        "    STRIP_OUTER_ARRAY = FALSE",
        "    COMMENT = 'One JSON object per line (manifest or record envelope).';",
        "",
    ]
    if source["type"] == "internal_stage":
        lines += [
            f"DEFINE STAGE {BRONZE}.LANDING_STAGE",
            f"    FILE_FORMAT = {BRONZE}.JSON_LINES",
            "    COMMENT = 'Credential-free internal stage for manual/CI batch uploads.';",
            "",
        ]
    else:
        sys.exit(f"build.py: source.type '{source['type']}' has no deployed definition here — "
                  f"see ingestion/reference/s3.sql for the (unverified) s3 route.")

    if landing["type"] == "native":
        lines += [
            f"DEFINE TABLE {landing['table_name']} (",
            "    PAYLOAD          VARCHAR       NOT NULL,",
            "    FILE_NAME        VARCHAR,",
            "    FILE_ROW_NUMBER  NUMBER,",
            "    FILE_CONTENT_KEY VARCHAR,",
            "    INGESTED_AT      TIMESTAMP_TZ  DEFAULT CURRENT_TIMESTAMP()",
            ")",
            "COMMENT = 'Raw landing table. One row per JSON line loaded from LANDING_STAGE via COPY INTO. Batches are identified by FILE_NAME.';",
        ]
    elif landing["type"] == "iceberg":
        iceberg = landing["iceberg"]
        lines += [
            f"DEFINE ICEBERG TABLE {landing['table_name']} (",
            "    PAYLOAD          VARCHAR       NOT NULL,",
            "    FILE_NAME        VARCHAR,",
            "    FILE_ROW_NUMBER  NUMBER,",
            "    FILE_CONTENT_KEY VARCHAR,",
            "    INGESTED_AT      TIMESTAMP_TZ",
            ")",
            f"CATALOG = 'SNOWFLAKE'",
            f"EXTERNAL_VOLUME = '{iceberg['external_volume']}'",
            f"BASE_LOCATION = '{iceberg['base_location']}';",
        ]
    else:
        sys.exit(f"build.py: unknown landing.type '{landing['type']}'")

    return "\n".join(lines) + "\n"


def gen_validated_tables(doc):
    lines = [
        "-- =============================================================================",
        "-- GENERATED by ingestion/build.py from ingestion/contract/ — do not hand-edit.",
        "-- One VALIDATED_<DATASET> table per contract dataset, columns/types derived",
        "-- directly from the contract so schema drift between the two is impossible.",
        "-- =============================================================================",
        "",
    ]
    for ds_name, ds in doc["datasets"].items():
        table = f"{SILVER}.VALIDATED_{ds_name.upper()}"
        col_lines = []
        for col_name, col in ds["columns"].items():
            sql_type = sql_column_type(col_name, col, f"datasets.{ds_name}.columns.{col_name}")
            not_null = "" if col.get("nullable", True) else " NOT NULL"
            col_lines.append(f"    {col_name.upper():<20} {sql_type}{not_null},")
        col_lines.append("    BATCH_ID             VARCHAR(200) NOT NULL,")
        pk_cols = ", ".join(c.upper() for c in ds["primary_key"])
        col_lines.append(f"    PRIMARY KEY ({pk_cols})")
        lines.append(f"DEFINE TABLE {table} (")
        lines += col_lines
        lines.append(")")
        version = doc["version"]
        lines.append(f"COMMENT = 'Validated {ds_name} dataset, current release only. Generated from contract v{version}.';")
        lines.append("")

    lines.append(f"DEFINE VIEW {METADATA}.REPORTING_CURRENT_RELEASE AS")
    lines.append("SELECT")
    lines.append("    p.CURRENT_BATCH_ID,")
    lines.append("    p.CURRENT_RELEASE_AT,")
    counts = ",\n".join(
        f"    (SELECT COUNT(*) FROM {SILVER}.VALIDATED_{ds_name.upper()}) AS {ds_name.upper()}_COUNT"
        for ds_name in doc["datasets"]
    )
    lines.append(counts)
    lines.append(f"FROM {CONTROL}.CONTROL_RELEASE_POINTER p")
    lines.append("WHERE p.POINTER_NAME = 'LOYALTY_SNAPSHOT';")
    return "\n".join(lines) + "\n"


def gen_lineage_schema(doc):
    """Schema only — DCM manages structure, not data. Row content (which
    object feeds which) is loaded by seed_lineage() below, since it's
    documentation data, not something a contract validates."""
    return "\n".join([
        "-- =============================================================================",
        "-- GENERATED by ingestion/build.py from ingestion/contract/ — do not hand-edit.",
        "-- Pipeline stage/dependency documentation. Rows loaded by",
        "-- `python ingestion/build.py --seed`, not by DCM (schema only here).",
        "-- =============================================================================",
        "",
        f"DEFINE TABLE {LINEAGE}.PIPELINE_STAGE_MAP (",
        "    DATABASE_NAME    VARCHAR(200)  NOT NULL,",
        "    SCHEMA_NAME      VARCHAR(200)  NOT NULL,",
        "    OBJECT_NAME      VARCHAR(200)  NOT NULL,",
        "    STAGE            VARCHAR(50)   NOT NULL,",
        "    UPSTREAM_OBJECT  VARCHAR(400),",
        "    DESCRIPTION      VARCHAR(1000),",
        "    PRIMARY KEY (DATABASE_NAME, SCHEMA_NAME, OBJECT_NAME)",
        ")",
        "COMMENT = 'Human-readable pipeline lineage: which object feeds which. Not a substitute for Snowflake ACCESS_HISTORY/OBJECT_DEPENDENCIES or dbt''s own manifest.json (both trace real object-level dependencies automatically) — this is documentation-as-data for people browsing the schema, kept in sync by ingestion/build.py --seed.';",
    ]) + "\n"


def gen_pii_registry_schema(doc):
    """Schema only — see gen_lineage_schema's note on schema-vs-data."""
    return "\n".join([
        "-- =============================================================================",
        "-- GENERATED by ingestion/build.py from ingestion/contract/ — do not hand-edit.",
        "-- PII column registry. Rows loaded by `python ingestion/build.py --seed`",
        "-- from the contract's pii/pii_kind tags (schema only here).",
        "-- =============================================================================",
        "",
        f"DEFINE TABLE {PII_CONTROL}.PII_COLUMN_REGISTRY (",
        "    TABLE_NAME            VARCHAR(200)  NOT NULL,",
        "    COLUMN_NAME           VARCHAR(200)  NOT NULL,",
        "    DATASET_NAME          VARCHAR(200)  NOT NULL,",
        "    PII_KIND              VARCHAR(100)  NOT NULL,",
        "    MASKING_POLICY_NAME   VARCHAR(400),",
        "    MASKING_ENFORCED      BOOLEAN       NOT NULL,",
        "    LOADED_AT             TIMESTAMP_TZ  DEFAULT CURRENT_TIMESTAMP(),",
        "    PRIMARY KEY (TABLE_NAME, COLUMN_NAME)",
        ")",
        "COMMENT = 'Governance registry of every column tagged pii:true in the contract. MASKING_ENFORCED is FALSE for all rows on this account: its Snowflake edition does not support masking policies at all (confirmed directly — see ingestion/reference/masking.sql). This table records governance intent even where enforcement is not live.';",
    ]) + "\n"


def gen_masking_reference(doc):
    """One reference file: policy definitions (would live in PII_CONTROL) +
    the column-attach step (targets SILVER tables). Both UNVERIFIED on this
    account (masking policies aren't supported by its edition at all —
    confirmed directly, independent of DCM), and DCM doesn't yet support
    attaching a policy to a column even where it is supported."""
    pii_cols = []  # (dataset, column, sql_type, pii_kind)
    for ds_name, ds in doc["datasets"].items():
        for col_name, col in ds["columns"].items():
            if col.get("pii"):
                pii_cols.append((ds_name, col_name, col["type"], col.get("pii_kind", "identifier")))

    if not pii_cols:
        return None

    pii_types = sorted({(t, k) for _, _, t, k in pii_cols})
    lines = [
        "-- UNVERIFIED — reference only, not deployed by DCM (lives outside sources/definitions).",
        "-- This Snowflake account's edition does not support masking policies at all —",
        "-- confirmed directly: `CREATE MASKING POLICY ...` errors with",
        "-- \"Unsupported feature 'MASKING POLICY'\" independent of DCM. This SQL is",
        "-- correct standard syntax; move the DEFINE block into sources/definitions/",
        "-- once run on an edition that supports masking policies (Enterprise+).",
        "--",
        "-- The ALTER TABLE block below is a further MANUAL step even then: DCM's",
        "-- DEFINE MASKING POLICY only creates the policy, not attaching it to a",
        "-- column — that isn't a supported DCM primitive yet.",
        "",
        "-- ---- policy definitions (would live in 05_PII_CONTROL) ----",
        "",
    ]
    for sql_type, pii_kind in pii_types:
        policy_name = f"{PII_CONTROL}.MASK_{pii_kind.upper()}_{sql_type.upper()}"
        col_type = "NUMBER" if sql_type == "integer" else "VARCHAR"
        lines += [
            f"DEFINE MASKING POLICY {policy_name} AS (val {col_type}) RETURNS {col_type} ->",
            "    CASE",
            "        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN val",
            "        ELSE NULL",
            "    END",
            f"COMMENT = 'Masks {pii_kind} columns of type {sql_type} for any role other than ACCOUNTADMIN.';",
            "",
        ]

    lines.append("-- ---- attach to columns in 01_SILVER (manual, after the policies above are deployed) ----")
    lines.append("")
    for ds_name, col_name, sql_type, pii_kind in pii_cols:
        table = f"{SILVER}.VALIDATED_{ds_name.upper()}"
        policy = f"{PII_CONTROL}.MASK_{pii_kind.upper()}_{sql_type.upper()}"
        lines.append(f"ALTER TABLE {table} MODIFY COLUMN {col_name.upper()} SET MASKING POLICY {policy};")

    return "\n".join(lines) + "\n"


def gen_s3_reference(doc):
    s3 = doc["ingestion"]["source"]["s3"]
    landing = doc["ingestion"]["landing"]
    lines = [
        "-- UNVERIFIED — reference only, not deployed by DCM (lives outside sources/definitions).",
        "-- No live AWS credentials in this account to test this route. Replace the",
        "-- REPLACE_* placeholders and move into sources/definitions/ once validated.",
        "",
        f"CREATE STORAGE INTEGRATION IF NOT EXISTS {s3['integration_name']}",
        "    TYPE = EXTERNAL_STAGE",
        "    STORAGE_PROVIDER = 'S3'",
        "    ENABLED = TRUE",
        f"    STORAGE_AWS_ROLE_ARN = '{s3['aws_role_arn']}'",
        f"    STORAGE_ALLOWED_LOCATIONS = ('{s3['bucket_url']}');",
        "",
        f"CREATE STAGE IF NOT EXISTS {s3['stage_name']}",
        f"    URL = '{s3['bucket_url']}'",
        f"    STORAGE_INTEGRATION = {s3['integration_name']}",
        f"    FILE_FORMAT = {BRONZE}.JSON_LINES;",
    ]
    if s3.get("auto_ingest"):
        lines += [
            "",
            f"CREATE PIPE IF NOT EXISTS {s3['pipe_name']}",
            "    AUTO_INGEST = TRUE",
            "AS",
            f"COPY INTO {landing['table_name']}",
            "    (PAYLOAD, FILE_NAME, FILE_ROW_NUMBER, FILE_CONTENT_KEY, INGESTED_AT)",
            "FROM (",
            "    SELECT",
            "        TO_JSON($1), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,",
            "        METADATA$FILE_CONTENT_KEY, METADATA$START_SCAN_TIME",
            f"    FROM @{s3['stage_name']}",
            ")",
            f"FILE_FORMAT = (FORMAT_NAME = {BRONZE}.JSON_LINES)",
            f"PATTERN = '{doc['ingestion']['source']['file_pattern']}'",
            "ON_ERROR = 'SKIP_FILE';",
        ]
    return "\n".join(lines) + "\n"


def seed_contract(connection, doc, contract_hash):
    """Loads the contract into CONTROL_DATA_CONTRACTS (data-plane, outside
    DCM's schema-only scope). Additive: an existing contract_id+version is
    left alone, so bumping `version` in the YAML is how you publish a change."""
    contract_json_text = json.dumps(doc)
    sql = f"""
    INSERT INTO {CONTROL}.CONTROL_DATA_CONTRACTS (CONTRACT_ID, VERSION, CONTRACT_JSON, CONTRACT_HASH)
    SELECT '{doc["contract_id"]}', {doc["version"]}, PARSE_JSON($${contract_json_text}$$), '{contract_hash}'
    WHERE NOT EXISTS (
        SELECT 1 FROM {CONTROL}.CONTROL_DATA_CONTRACTS
        WHERE CONTRACT_ID = '{doc["contract_id"]}' AND VERSION = {doc["version"]}
    );
    """
    subprocess.run(["snow", "sql", "-c", connection, "-q", sql], check=True)
    print(f"Seeded contract {doc['contract_id']} v{doc['version']}, hash={contract_hash}")


def seed_pii_registry(connection, doc):
    """Always reflects the current contract exactly — replace-all rather
    than additive, unlike the contract table itself."""
    rows = []
    for ds_name, ds in doc["datasets"].items():
        table = f"VALIDATED_{ds_name.upper()}"
        for col_name, col in ds["columns"].items():
            if col.get("pii"):
                pii_kind = col.get("pii_kind", "identifier")
                policy = f"MASK_{pii_kind.upper()}_{col['type'].upper()}"
                rows.append((table, col_name.upper(), ds_name, pii_kind, policy))

    values_sql = ",\n        ".join(
        f"('{t}', '{c}', '{d}', '{p}', '{pol}', FALSE)" for t, c, d, p, pol in rows
    )
    sql = f"""
    DELETE FROM {PII_CONTROL}.PII_COLUMN_REGISTRY;
    INSERT INTO {PII_CONTROL}.PII_COLUMN_REGISTRY
        (TABLE_NAME, COLUMN_NAME, DATASET_NAME, PII_KIND, MASKING_POLICY_NAME, MASKING_ENFORCED)
    VALUES
        {values_sql};
    """
    subprocess.run(["snow", "sql", "-c", connection, "-q", sql], check=True)
    print(f"Seeded {len(rows)} PII column registry rows")


def seed_lineage(doc):
    """Static-ish documentation rows: bronze -> silver -> control chain per
    dataset, plus the dbt-owned stages downstream. Replace-all, same as the
    PII registry — this always reflects the current contract + known dbt
    layer, not an append-only history."""
    rows = [
        ("NERO_DB", '00_BRONZE', "RAW_ENVELOPES", "bronze", None,
         "Raw JSON envelopes for all datasets, unvalidated."),
    ]
    for ds_name in doc["datasets"]:
        upper = ds_name.upper()
        rows += [
            ("NERO_DB", '01_SILVER', f"VALIDATED_{upper}", "silver",
             "NERO_DB.00_BRONZE.RAW_ENVELOPES -> NERO_DB.02_CONTROL.PROCESS_BATCH",
             f"Contract-validated {ds_name}, written by PROCESS_BATCH on publish."),
            ("NERO_ANALYTICS", '00_STAGING', f"STG_{upper}", "dbt_staging",
             f"NERO_DB.01_SILVER.VALIDATED_{upper}",
             f"dbt staging view over VALIDATED_{upper}."),
        ]
    rows += [
        ("NERO_ANALYTICS", '02_GOLD', "DIM_* / FACT_*", "dbt_gold",
         "NERO_ANALYTICS.00_STAGING.STG_*",
         "Kimball dimensions/facts built from staging (+ 01_SNAPSHOTS for customer SCD2)."),
        ("NERO_ANALYTICS", '03_MART_MARKETING', "MART_*", "dbt_mart",
         "NERO_ANALYTICS.02_GOLD.DIM_*/FACT_*",
         "Marketing reporting marts."),
        ("NERO_ANALYTICS", '04_MART_OPERATIONS', "MART_*", "dbt_mart",
         "NERO_ANALYTICS.02_GOLD.DIM_*/FACT_*",
         "Operations reporting marts."),
    ]

    def esc(s):
        return s.replace("'", "''") if s else s

    values_sql = ",\n        ".join(
        "('{}', '{}', '{}', '{}', {}, '{}')".format(
            db, schema, obj, stage,
            f"'{esc(upstream)}'" if upstream else "NULL",
            esc(desc),
        )
        for db, schema, obj, stage, upstream, desc in rows
    )
    return f"""
    DELETE FROM {LINEAGE}.PIPELINE_STAGE_MAP;
    INSERT INTO {LINEAGE}.PIPELINE_STAGE_MAP
        (DATABASE_NAME, SCHEMA_NAME, OBJECT_NAME, STAGE, UPSTREAM_OBJECT, DESCRIPTION)
    VALUES
        {values_sql};
    """


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", action="store_true",
                         help="also load the contract, PII registry, and lineage map with data")
    parser.add_argument("-c", "--connection", help="snow CLI connection name (required with --seed)")
    args = parser.parse_args()
    if args.seed and not args.connection:
        sys.exit("build.py: --seed requires -c/--connection")

    doc, contract_hash = load_contract()

    definitions_dir = ROOT / "sources" / "definitions" / "ingestion"
    reference_dir = ROOT / "ingestion" / "reference"
    definitions_dir.mkdir(parents=True, exist_ok=True)
    reference_dir.mkdir(parents=True, exist_ok=True)

    (definitions_dir / "raw.sql").write_text(gen_raw_landing(doc))
    (definitions_dir / "validated.sql").write_text(gen_validated_tables(doc))
    (definitions_dir / "lineage.sql").write_text(gen_lineage_schema(doc))
    (definitions_dir / "pii_registry.sql").write_text(gen_pii_registry_schema(doc))

    masking_sql = gen_masking_reference(doc)
    masking_path = reference_dir / "masking.sql"
    if masking_sql:
        masking_path.write_text(masking_sql)
    elif masking_path.exists():
        masking_path.unlink()

    (reference_dir / "s3.sql").write_text(gen_s3_reference(doc))

    print(f"Built from ingestion/contract/ (contract v{doc['version']}, hash={contract_hash})")
    print("Generated (DCM-managed, deployed):")
    print("  sources/definitions/ingestion/raw.sql")
    print("  sources/definitions/ingestion/validated.sql")
    print("  sources/definitions/ingestion/lineage.sql")
    print("  sources/definitions/ingestion/pii_registry.sql")
    print("Generated (reference only, NOT deployed by DCM):")
    print("  ingestion/reference/s3.sql (unverified — no live AWS credentials)")
    if masking_sql:
        print("  ingestion/reference/masking.sql (unverified — account edition lacks masking policy support)")

    if args.seed:
        seed_contract(args.connection, doc, contract_hash)
        seed_pii_registry(args.connection, doc)
        subprocess.run(["snow", "sql", "-c", args.connection, "-q", seed_lineage(doc)], check=True)
        print("Seeded lineage map")


if __name__ == "__main__":
    main()
