-- =============================================================================
-- Daily pipeline orchestration: a real Snowflake task DAG, so dbt build
-- runs strictly after both ingestion tasks succeed, not just at a fixed
-- cron time offset. The previous setup ran three independently-scheduled
-- tasks 15-30 minutes apart, a guess at "enough headroom", with no actual
-- dependency: a slow or failed ingestion run would not stop dbt from
-- building against stale or partial data.
--
-- Snowflake requires every task in one DAG to share the same owner role
-- and live in the same schema. EXECUTE DBT PROJECT further requires its
-- task to live in the dbt project's own schema
-- (NERO_ANALYTICS.DBT_PROJECT). account_setup/synthetic_daily_dbt_refresh.sql
-- previously avoided an AFTER dependency for this reason, calling
-- cross-owner/cross-schema dependencies "fragility" -- in fact it is a
-- hard constraint, a DAG spanning NERO_DB."02_CONTROL" (ACCOUNTADMIN) and
-- NERO_ANALYTICS.DBT_PROJECT (NERO_DBT_ROLE) is not possible at all, not
-- just fragile. The fix is to consolidate: both ingestion tasks move into
-- NERO_ANALYTICS.DBT_PROJECT, owned by NERO_DBT_ROLE, alongside
-- DBT_DAILY_REFRESH_TASK. The ingestion procedures themselves are
-- unchanged -- still owned by ACCOUNTADMIN, still defined in
-- account_setup/synthetic_daily_ingest.sql and
-- ingestion/generated/google_sheets_procedure.sql, and still run with
-- their own owner's rights (no EXECUTE AS CALLER), so NERO_DBT_ROLE only
-- needs USAGE to trigger them, not the underlying data access those
-- procedures themselves run with.
--
-- Graph:
--   SYNTHETIC_DAILY_INGEST_TASK (root, 06:00 UTC)
--     -> GOOGLE_SHEETS_INGEST_TASK
--          -> DBT_DAILY_REFRESH_TASK (runs only if both predecessors succeed)
--
-- Supersedes the CREATE TASK blocks in:
--   - account_setup/synthetic_daily_ingest.sql (the procedure it defines
--     is unchanged and still applies from there)
--   - ingestion/generated/google_sheets_procedure.sql (regenerated by
--     ingestion/build.py to no longer emit a task at all; the procedure
--     it defines is unchanged)
--   - account_setup/synthetic_daily_dbt_refresh.sql (superseded entirely)
--
-- Apply with: snow sql -f account_setup/daily_pipeline_orchestration.sql
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- Owner's-rights procedures (no EXECUTE AS CALLER) -- NERO_DBT_ROLE only
-- needs USAGE to call them, nothing about the underlying staging tables.
GRANT USAGE ON SCHEMA NERO_DB."02_CONTROL" TO ROLE NERO_DBT_ROLE;
GRANT USAGE ON PROCEDURE NERO_DB."02_CONTROL".GENERATE_SYNTHETIC_DAY() TO ROLE NERO_DBT_ROLE;
GRANT USAGE ON PROCEDURE NERO_DB."02_CONTROL".INGEST_FROM_GOOGLE_SHEETS() TO ROLE NERO_DBT_ROLE;
GRANT USAGE ON WAREHOUSE NERO_LOAD_WH TO ROLE NERO_DBT_ROLE;

-- Old, independently-scheduled tasks -- drop so there is exactly one
-- daily trigger per procedure, not two racing each other.
DROP TASK IF EXISTS NERO_DB."02_CONTROL".SYNTHETIC_DAILY_INGEST_TASK;
DROP TASK IF EXISTS NERO_DB."02_CONTROL".GOOGLE_SHEETS_INGEST_TASK;

USE ROLE NERO_DBT_ROLE;

CREATE OR REPLACE TASK NERO_ANALYTICS.DBT_PROJECT.SYNTHETIC_DAILY_INGEST_TASK
  WAREHOUSE = 'NERO_LOAD_WH'
  SCHEDULE = 'USING CRON 0 6 * * * UTC'
  COMMENT = 'Root of the daily pipeline DAG. Runs GENERATE_SYNTHETIC_DAY(); GOOGLE_SHEETS_INGEST_TASK and DBT_DAILY_REFRESH_TASK follow via AFTER. See account_setup/daily_pipeline_orchestration.sql.'
AS
  CALL NERO_DB."02_CONTROL".GENERATE_SYNTHETIC_DAY();

CREATE OR REPLACE TASK NERO_ANALYTICS.DBT_PROJECT.GOOGLE_SHEETS_INGEST_TASK
  WAREHOUSE = 'NERO_LOAD_WH'
  COMMENT = 'Runs INGEST_FROM_GOOGLE_SHEETS() after the synthetic generator succeeds. See account_setup/daily_pipeline_orchestration.sql.'
  AFTER NERO_ANALYTICS.DBT_PROJECT.SYNTHETIC_DAILY_INGEST_TASK
AS
  CALL NERO_DB."02_CONTROL".INGEST_FROM_GOOGLE_SHEETS();

CREATE OR REPLACE TASK NERO_ANALYTICS.DBT_PROJECT.DBT_DAILY_REFRESH_TASK
  WAREHOUSE = 'NERO_DBT_WH'
  COMMENT = 'Rebuilds bronze/silver/gold/marts. Runs only once both ingestion tasks in the DAG have succeeded -- not a fixed time offset. See account_setup/daily_pipeline_orchestration.sql.'
  AFTER NERO_ANALYTICS.DBT_PROJECT.SYNTHETIC_DAILY_INGEST_TASK, NERO_ANALYTICS.DBT_PROJECT.GOOGLE_SHEETS_INGEST_TASK
AS
  EXECUTE DBT PROJECT NERO_ANALYTICS.DBT_PROJECT.NERO_ANALYTICS ARGS = 'build';

-- Resume leaf-to-root, per Snowflake's own guidance for resuming a DAG
-- (resuming the root first, while a successor is still suspended, can
-- deadlock the graph).
ALTER TASK NERO_ANALYTICS.DBT_PROJECT.DBT_DAILY_REFRESH_TASK RESUME;
ALTER TASK NERO_ANALYTICS.DBT_PROJECT.GOOGLE_SHEETS_INGEST_TASK RESUME;
ALTER TASK NERO_ANALYTICS.DBT_PROJECT.SYNTHETIC_DAILY_INGEST_TASK RESUME;
