-- =============================================================================
-- Google Sheets ingestion, prerequisite infrastructure: network rule and
-- external access integration. Apply THIS FILE FIRST.
--
-- The procedure, its scheduled task, and its grants live in
-- ingestion/generated/google_sheets_procedure.sql instead, generated by
-- `python ingestion/build.py`, and must be applied SECOND -- for two
-- reasons, not one file split arbitrarily:
--   1. CREATE PROCEDURE ... EXTERNAL_ACCESS_INTEGRATIONS = (...) requires
--      the integration below to already exist.
--   2. GRANT USAGE ON PROCEDURE requires the procedure to already exist,
--      so the task and grants have to come after CREATE PROCEDURE, not
--      before it -- which is why they are generated alongside the
--      procedure rather than kept here.
--
-- The procedure's URLs and column types come from
-- ingestion.sources[google_sheets_feed] in ingestion/contract/meta.yaml
-- and ingestion/contract/datasets/ -- edit the contract, not the
-- generated file, and rerun the generator.
--
-- All 4 datasets stay full-mode: a Google Sheets CSV export has no concept
-- of "just the changed rows" -- every fetch returns the whole sheet, so
-- there's no watermark to track here. (Contrast with the synthetic daily
-- generator's transactions feed, which genuinely is incremental -- see
-- account_setup/synthetic_daily_ingest.sql.)
--
-- Not true Snowpipe -- Google Sheets isn't S3/GCS/Azure Blob, so there's no
-- cloud event-notification integration Snowflake can subscribe to. This is
-- the honest alternative: a scheduled Task (automatic trigger) wrapping a
-- stored procedure that's also directly callable (manual trigger) --
-- functionally the same duality real Snowpipe offers (auto-ingest vs.
-- REST-triggered), just polling instead of event-driven.
--
-- Apply with: snow sql -f account_setup/google_sheets_ingest.sql
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- Redirects observed live: docs.google.com -> a wildcard
-- doc-XX-XX-sheets.googleusercontent.com host that varies per request, so
-- both need to be allowlisted or the redirect leg of the fetch fails.
CREATE NETWORK RULE IF NOT EXISTS NERO_DB."02_CONTROL".GOOGLE_SHEETS_NETWORK_RULE
  TYPE = HOST_PORT
  MODE = EGRESS
  VALUE_LIST = ('docs.google.com', '*.googleusercontent.com')
  COMMENT = 'Egress allowlist for fetching public Google Sheets CSV exports -- nothing else.';

CREATE EXTERNAL ACCESS INTEGRATION IF NOT EXISTS NERO_GOOGLE_SHEETS_ACCESS_INTEGRATION
  ALLOWED_NETWORK_RULES = (NERO_DB."02_CONTROL".GOOGLE_SHEETS_NETWORK_RULE)
  ENABLED = TRUE
  COMMENT = 'Lets INGEST_FROM_GOOGLE_SHEETS() fetch public Sheets CSV exports. Scoped to Google Sheets export hosts only.';

ALTER EXTERNAL ACCESS INTEGRATION NERO_GOOGLE_SHEETS_ACCESS_INTEGRATION
  SET ALLOWED_NETWORK_RULES = (NERO_DB."02_CONTROL".GOOGLE_SHEETS_NETWORK_RULE);
