-- =============================================================================
-- Five department-leader chatbots, each a separate least-privilege
-- persona -- the same "one app per role" pattern established for
-- NERO_BI_ROLE (business) and NERO_GOVERNANCE_ROLE (platform engineer):
-- Snowflake Streamlit apps always execute with the OWNER's privileges (no
-- per-viewer execute-as-caller, and GRANT OWNERSHIP ON STREAMLIT isn't
-- supported), so "role-based" means separate app instances each owned by
-- a role scoped to exactly the tools that persona should reach.
--
--   Marketing (CMO)      -> loyalty_analyst only
--   Store Ops (COO)      -> loyalty_analyst only (same data, ops framing)
--   Finance (CFO)        -> loyalty_analyst + governance_analyst
--   Security lead (CISO) -> findings_search only
--   Platform lead (CTO)  -> governance_analyst + findings_search
--
-- Verified live under each role's own connection before shipping: a real
-- agent call per persona, and the full chat_store create/save/list cycle.
-- Caught and fixed a real bug this way -- the first grant pass gave
-- Marketing/Ops/Finance REFERENCES on LOYALTY_SEMANTIC_VIEW but not
-- SELECT on the underlying NERO_DB."01_BRONZE" tables the semantic view
-- queries; semantic views do NOT run with definer's rights, the querying
-- role needs its own direct access to the base tables (same lesson
-- NERO_BI_ROLE and NERO_GOVERNANCE_ROLE had already encoded, just missed
-- when this file was first drafted). Fixed below; the queries failed with
-- "doesn't exist or isn't accessible" before the fix and answered
-- correctly after.
--
-- Apply with a Python session, not `snow sql -f` (same CLI templating
-- limitation as cortex_chatbot_stack.sql / governance_chatbot_stack.sql).
-- =============================================================================


-- ================= NERO_MARKETING_ROLE =================
CREATE ROLE IF NOT EXISTS NERO_MARKETING_ROLE
  COMMENT = 'CMO / Marketing lead persona: loyalty engagement data only (signups, tiers, redemption).';

CREATE USER IF NOT EXISTS NERO_MARKETING_USER
  TYPE = SERVICE
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqyZwk8tHXFYl+nVfkoKPOrmlcotx2zUuW5f0vFh25bjSAFHm1kC8i8pHPUz1Ge6oVeKTtrMwWLvC9UBZ6GskeAxn2hAJB4HFgupA53kZunK+S/+yn1Wj2Wtpw2d4dGKILC9nGSfa608Qj9yOjLZkbMZF1XiCW1t6rg8Nd19vKDiNagQLeNv9QwOosRhaswUvngriPwzydY3/kuoRjK9ziW1JQcinq3k1QeppHJ0UubZIWZSu+dIyb1Rt3y2ezT0cpFAmTQCxve6bqj8VBdEwHJNzYpKZc4OseaX1gRAxkyVVn618q2dwEJsCSZ1j03bydMjPwZq33rNE7KrCkc6DgwIDAQAB'
  DEFAULT_ROLE = NERO_MARKETING_ROLE
  DEFAULT_WAREHOUSE = NERO_BI_WH
  COMMENT = 'Service identity owning the NERO_MARKETING persona chatbot (leader_chatbots_app/).';

GRANT ROLE NERO_MARKETING_ROLE TO USER NERO_MARKETING_USER;

GRANT USAGE ON WAREHOUSE NERO_BI_WH TO ROLE NERO_MARKETING_ROLE;
GRANT USAGE ON DATABASE NERO_GOVERNANCE TO ROLE NERO_MARKETING_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.CORTEX_TOOLS TO ROLE NERO_MARKETING_ROLE;
GRANT USAGE ON INTEGRATION NERO_PYPI_ACCESS_INTEGRATION TO ROLE NERO_MARKETING_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_MARKETING_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_MARKETING_ROLE;


GRANT USAGE ON DATABASE NERO_DB TO ROLE NERO_MARKETING_ROLE;
GRANT REFERENCES ON SEMANTIC VIEW NERO_GOVERNANCE.CORTEX_TOOLS.LOYALTY_SEMANTIC_VIEW TO ROLE NERO_MARKETING_ROLE;
-- Semantic views do not run with definer's rights -- the querying role
-- needs its own direct access to the underlying base tables:
GRANT USAGE ON SCHEMA NERO_DB."01_BRONZE" TO ROLE NERO_MARKETING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA NERO_DB."01_BRONZE" TO ROLE NERO_MARKETING_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NERO_DB."01_BRONZE" TO ROLE NERO_MARKETING_ROLE;

-- ================= NERO_OPS_ROLE =================
CREATE ROLE IF NOT EXISTS NERO_OPS_ROLE
  COMMENT = 'COO / Store Operations lead persona: same loyalty/sales data as marketing, operations-focused questions (basket, visits, store/format/region).';

CREATE USER IF NOT EXISTS NERO_OPS_USER
  TYPE = SERVICE
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA00rqU+Ub70wR89svTJzoBAB4ju9/NST4tITvHzJ9xiew7AQLWV8vaGpshy1Q7bU91HoTY99xJzWclEzmK6Or0dgYqVXuJc1Zxskn1wMmqTvqfiuzcmYFVfgZ6fVuZsExhopk71oLj3wF0zeGCyf69lwg+47AqxQZXhD1eaFH5MxqgtaXJcycBJzg3exVjIE6rerYbEwpxSzWfobr9wBoj0a8kC22wXZYA0qtauDEKKyeINWWYmC/XX6FIi0twZ6mnWefYKq0Zizu6U8drc0WGESLdfiW6ibV6n5ZYNVIg1z0jiVeX+3XPctbkmGGyQdsQLbbhkYKctzJAZCsdAiHbwIDAQAB'
  DEFAULT_ROLE = NERO_OPS_ROLE
  DEFAULT_WAREHOUSE = NERO_BI_WH
  COMMENT = 'Service identity owning the NERO_OPS persona chatbot (leader_chatbots_app/).';

GRANT ROLE NERO_OPS_ROLE TO USER NERO_OPS_USER;

GRANT USAGE ON WAREHOUSE NERO_BI_WH TO ROLE NERO_OPS_ROLE;
GRANT USAGE ON DATABASE NERO_GOVERNANCE TO ROLE NERO_OPS_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.CORTEX_TOOLS TO ROLE NERO_OPS_ROLE;
GRANT USAGE ON INTEGRATION NERO_PYPI_ACCESS_INTEGRATION TO ROLE NERO_OPS_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_OPS_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_OPS_ROLE;


GRANT USAGE ON DATABASE NERO_DB TO ROLE NERO_OPS_ROLE;
GRANT REFERENCES ON SEMANTIC VIEW NERO_GOVERNANCE.CORTEX_TOOLS.LOYALTY_SEMANTIC_VIEW TO ROLE NERO_OPS_ROLE;
-- Semantic views do not run with definer's rights -- the querying role
-- needs its own direct access to the underlying base tables:
GRANT USAGE ON SCHEMA NERO_DB."01_BRONZE" TO ROLE NERO_OPS_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA NERO_DB."01_BRONZE" TO ROLE NERO_OPS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NERO_DB."01_BRONZE" TO ROLE NERO_OPS_ROLE;

-- ================= NERO_FINANCE_ROLE =================
CREATE ROLE IF NOT EXISTS NERO_FINANCE_ROLE
  COMMENT = 'CFO / Finance lead persona: sales revenue (loyalty semantic view) AND platform compute cost/budget (governance semantic view).';

CREATE USER IF NOT EXISTS NERO_FINANCE_USER
  TYPE = SERVICE
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoeDBO0O0ZFqah2PfX1qBLJxd01Y/YqHTFF4qHkTlQqYYo7jOy8WQWE2bwKl/RBjeFowUsFxvvyjQWhkHsJVs89lE6frqT/kRwAJ4SS3m3e8zMUikSFy46L2aakhbg71LUCI6Cm4j+2vNrcMm7N61Q1bFTflIjkhoiD0+J1nEdR2xr6HAj8zkX1REuQnpPWciOXTUtqKUmZy5vFUzm/VH2qyDTX23Tcb2LG5Y1QoOA7UXj3BT+Rgsl2mdmrCCh3JXuuLO4PHJkBQs5A1RwBG8SlEK/FSxqS8+OIoVyWrqmJ93Gb/oUAsGSLOPJvisIjSsVBc/c7IoxpjTSA+ofcaC7QIDAQAB'
  DEFAULT_ROLE = NERO_FINANCE_ROLE
  DEFAULT_WAREHOUSE = NERO_BI_WH
  COMMENT = 'Service identity owning the NERO_FINANCE persona chatbot (leader_chatbots_app/).';

GRANT ROLE NERO_FINANCE_ROLE TO USER NERO_FINANCE_USER;

GRANT USAGE ON WAREHOUSE NERO_BI_WH TO ROLE NERO_FINANCE_ROLE;
GRANT USAGE ON DATABASE NERO_GOVERNANCE TO ROLE NERO_FINANCE_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.CORTEX_TOOLS TO ROLE NERO_FINANCE_ROLE;
GRANT USAGE ON INTEGRATION NERO_PYPI_ACCESS_INTEGRATION TO ROLE NERO_FINANCE_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_FINANCE_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_FINANCE_ROLE;


GRANT USAGE ON DATABASE NERO_DB TO ROLE NERO_FINANCE_ROLE;
GRANT REFERENCES ON SEMANTIC VIEW NERO_GOVERNANCE.CORTEX_TOOLS.LOYALTY_SEMANTIC_VIEW TO ROLE NERO_FINANCE_ROLE;
-- Semantic views do not run with definer's rights -- the querying role
-- needs its own direct access to the underlying base tables:
GRANT USAGE ON SCHEMA NERO_DB."01_BRONZE" TO ROLE NERO_FINANCE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA NERO_DB."01_BRONZE" TO ROLE NERO_FINANCE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NERO_DB."01_BRONZE" TO ROLE NERO_FINANCE_ROLE;


GRANT USAGE ON SCHEMA NERO_GOVERNANCE.COST TO ROLE NERO_FINANCE_ROLE;
GRANT SELECT ON TABLE NERO_GOVERNANCE.COST.WAREHOUSE_BUDGET TO ROLE NERO_FINANCE_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA NERO_GOVERNANCE.COST TO ROLE NERO_FINANCE_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA NERO_GOVERNANCE.COST TO ROLE NERO_FINANCE_ROLE;
GRANT REFERENCES ON SEMANTIC VIEW NERO_GOVERNANCE.CORTEX_TOOLS.GOVERNANCE_SEMANTIC_VIEW TO ROLE NERO_FINANCE_ROLE;

-- ================= NERO_SECURITY_LEAD_ROLE =================
CREATE ROLE IF NOT EXISTS NERO_SECURITY_LEAD_ROLE
  COMMENT = 'CISO / Security lead persona: security/Trust Center findings only -- no business or cost data at all.';

CREATE USER IF NOT EXISTS NERO_SECURITY_LEAD_USER
  TYPE = SERVICE
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApB4NwvLH/W5jJv+DK1+VghKvlE0SipCnAMyRxYvuUuu4M18sMamMQQ6uTUELa1Iu8sl5jjST/io83XR5kMBpCLVgBw4QD5tmarlGXKfjK0PTHnw6rcD7J7ZDdmIidsLlfMPZIqpCu8yaBk82S0dgEMjKvG83ho3WHpAK5DlTvAAwUkbIhqwkKufr5565z1992MG14740ygpjGx5MwFUwwSLeTKAuCPlNwQh0IAQ/76QZI+7yTiYvRPXR+L4g+VpkMkb5/KX1YQ0Rn24shP5mx+aYL8E0E3s9tdCqbWhv21LPli3eyqME82GsWpHtP6/V6pdmdOfMVTvjD87PRGWeFQIDAQAB'
  DEFAULT_ROLE = NERO_SECURITY_LEAD_ROLE
  DEFAULT_WAREHOUSE = NERO_BI_WH
  COMMENT = 'Service identity owning the NERO_SECURITY_LEAD persona chatbot (leader_chatbots_app/).';

GRANT ROLE NERO_SECURITY_LEAD_ROLE TO USER NERO_SECURITY_LEAD_USER;

GRANT USAGE ON WAREHOUSE NERO_BI_WH TO ROLE NERO_SECURITY_LEAD_ROLE;
GRANT USAGE ON DATABASE NERO_GOVERNANCE TO ROLE NERO_SECURITY_LEAD_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.CORTEX_TOOLS TO ROLE NERO_SECURITY_LEAD_ROLE;
GRANT USAGE ON INTEGRATION NERO_PYPI_ACCESS_INTEGRATION TO ROLE NERO_SECURITY_LEAD_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_SECURITY_LEAD_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_SECURITY_LEAD_ROLE;


GRANT USAGE ON SCHEMA NERO_GOVERNANCE.SECURITY TO ROLE NERO_SECURITY_LEAD_ROLE;
GRANT USAGE ON CORTEX SEARCH SERVICE NERO_GOVERNANCE.SECURITY.FINDINGS_SEARCH_SVC TO ROLE NERO_SECURITY_LEAD_ROLE;
GRANT SELECT ON TABLE NERO_GOVERNANCE.SECURITY.FINDINGS_DOCS TO ROLE NERO_SECURITY_LEAD_ROLE;

-- ================= NERO_PLATFORM_LEAD_ROLE =================
CREATE ROLE IF NOT EXISTS NERO_PLATFORM_LEAD_ROLE
  COMMENT = 'CTO / Platform lead persona: platform cost/budget AND security posture -- engineering-oriented, no business/loyalty data.';

CREATE USER IF NOT EXISTS NERO_PLATFORM_LEAD_USER
  TYPE = SERVICE
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl3diWNJgz+MKWABzPTPkQjpgdSp8LW/lus28/KbxShPoJC0P79w52YYQkNHJAE8rYYw75lQmj4/fbraQzyUwKhIY3Jx6ArfvOd9tuRPSX77W22OLglLeU2Tuo6i8xr7XgVfLwFJid9+tTZwcln5qSYWlxFHa2UX2DNVtfv+JrNq49q2qAWfmU9YvX/BjF82fpgWMWR3qlTrSgnk+qnWgBwQO2U7C7ar6rxWWzvAisqtDnf7IVEvWqG+ymQE6Yfoln2WOl5NErRo5G6ojydPeV7LSOcinIaozv3iJFbfhTvr/TW9AlacfDQbWEXYrAuOS4SeAo5nQMZGdvUJc11200QIDAQAB'
  DEFAULT_ROLE = NERO_PLATFORM_LEAD_ROLE
  DEFAULT_WAREHOUSE = NERO_BI_WH
  COMMENT = 'Service identity owning the NERO_PLATFORM_LEAD persona chatbot (leader_chatbots_app/).';

GRANT ROLE NERO_PLATFORM_LEAD_ROLE TO USER NERO_PLATFORM_LEAD_USER;

GRANT USAGE ON WAREHOUSE NERO_BI_WH TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT USAGE ON DATABASE NERO_GOVERNANCE TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.CORTEX_TOOLS TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT USAGE ON INTEGRATION NERO_PYPI_ACCESS_INTEGRATION TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_PLATFORM_LEAD_ROLE;


GRANT USAGE ON SCHEMA NERO_GOVERNANCE.COST TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT SELECT ON TABLE NERO_GOVERNANCE.COST.WAREHOUSE_BUDGET TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA NERO_GOVERNANCE.COST TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA NERO_GOVERNANCE.COST TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT REFERENCES ON SEMANTIC VIEW NERO_GOVERNANCE.CORTEX_TOOLS.GOVERNANCE_SEMANTIC_VIEW TO ROLE NERO_PLATFORM_LEAD_ROLE;


GRANT USAGE ON SCHEMA NERO_GOVERNANCE.SECURITY TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT USAGE ON CORTEX SEARCH SERVICE NERO_GOVERNANCE.SECURITY.FINDINGS_SEARCH_SVC TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT SELECT ON TABLE NERO_GOVERNANCE.SECURITY.FINDINGS_DOCS TO ROLE NERO_PLATFORM_LEAD_ROLE;
