-- =============================================================================
-- Five MORE department-leader chatbots, extending leader_personas_stack.sql
-- (Marketing/Ops/Finance/Security-lead/Platform-lead) with a second wave:
--
--   CEO                      -> loyalty_analyst + governance_analyst + findings_search (all three)
--   Customer Experience lead -> loyalty_analyst only (customer-behavior framing)
--   CDO / Data & Analytics   -> loyalty_analyst + governance_analyst (data-platform-health framing)
--   Internal Audit / Compliance -> findings_search only (audit framing)
--   Regional Director        -> loyalty_analyst + findings_search (new combination)
--
-- Same pattern throughout: one least-privilege role per persona, each
-- owning its own Streamlit app (deployed via that role's own connection,
-- since GRANT OWNERSHIP ON STREAMLIT isn't supported). The loyalty grants
-- already include the SELECT-on-01_SILVER fix discovered the first time
-- around -- REFERENCES on the semantic view alone is not enough; the
-- querying role needs direct access to the underlying base tables too.
--
-- Apply with a Python session, not `snow sql -f` (same CLI templating
-- limitation as the other *_stack.sql files in this directory).
-- =============================================================================


-- ================= NERO_CEO_ROLE =================
CREATE ROLE IF NOT EXISTS NERO_CEO_ROLE
  COMMENT = 'CEO persona: full cross-domain read access -- loyalty/sales, platform cost, and security findings. The only persona with all three tools.';

CREATE USER IF NOT EXISTS NERO_CEO_USER
  TYPE = SERVICE
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+zNX0Yzw8VXpYbsDwuljTH5tZoreI5BF3sWqekcz0PfSKDjL3z0Ah4BE0WKthcYs3khKV7AWrGhMBCTKguUzBhVbyfGtd1I4rO7hy+BmK72XYZaZIxg0h48Ube/NssHopE/RRz5RELpZBPli0q14wA8AQN2f/3ArLUkwaT+pO8aXX2UAj39/2GBzX5ooR1fZ043B7nW92d4A5STeP6mDPbyF25zfhoNJvPHDHEckq4I2IEIi3t8mYaD5o6hPIY58HcKgEhIP8rphnc9XMXmlPLbu9RBMKISeoch61hLg0E7ofOmTdvp9CVLCjXddWKmt0dhx1+LXa8Y9O8i/f/vHlQIDAQAB'
  DEFAULT_ROLE = NERO_CEO_ROLE
  DEFAULT_WAREHOUSE = NERO_BI_WH
  COMMENT = 'Service identity owning the NERO_CEO persona chatbot (leader_chatbots_app/).';

GRANT ROLE NERO_CEO_ROLE TO USER NERO_CEO_USER;

GRANT USAGE ON WAREHOUSE NERO_BI_WH TO ROLE NERO_CEO_ROLE;
GRANT USAGE ON DATABASE NERO_GOVERNANCE TO ROLE NERO_CEO_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.CORTEX_TOOLS TO ROLE NERO_CEO_ROLE;
GRANT USAGE ON INTEGRATION NERO_PYPI_ACCESS_INTEGRATION TO ROLE NERO_CEO_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_CEO_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_CEO_ROLE;


GRANT USAGE ON DATABASE NERO_DB TO ROLE NERO_CEO_ROLE;
GRANT USAGE ON SCHEMA NERO_DB.NERO_LOYALTY TO ROLE NERO_CEO_ROLE;
GRANT REFERENCES ON SEMANTIC VIEW NERO_DB.NERO_LOYALTY.LOYALTY_SEMANTIC_VIEW TO ROLE NERO_CEO_ROLE;
GRANT USAGE ON SCHEMA NERO_DB."01_SILVER" TO ROLE NERO_CEO_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA NERO_DB."01_SILVER" TO ROLE NERO_CEO_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NERO_DB."01_SILVER" TO ROLE NERO_CEO_ROLE;


GRANT USAGE ON SCHEMA NERO_GOVERNANCE.COST TO ROLE NERO_CEO_ROLE;
GRANT SELECT ON TABLE NERO_GOVERNANCE.COST.WAREHOUSE_BUDGET TO ROLE NERO_CEO_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA NERO_GOVERNANCE.COST TO ROLE NERO_CEO_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA NERO_GOVERNANCE.COST TO ROLE NERO_CEO_ROLE;
GRANT REFERENCES ON SEMANTIC VIEW NERO_GOVERNANCE.CORTEX_TOOLS.GOVERNANCE_SEMANTIC_VIEW TO ROLE NERO_CEO_ROLE;


GRANT USAGE ON SCHEMA NERO_GOVERNANCE.SECURITY TO ROLE NERO_CEO_ROLE;
GRANT USAGE ON CORTEX SEARCH SERVICE NERO_GOVERNANCE.SECURITY.FINDINGS_SEARCH_SVC TO ROLE NERO_CEO_ROLE;
GRANT SELECT ON TABLE NERO_GOVERNANCE.SECURITY.FINDINGS_DOCS TO ROLE NERO_CEO_ROLE;

-- ================= NERO_CX_ROLE =================
CREATE ROLE IF NOT EXISTS NERO_CX_ROLE
  COMMENT = 'Customer Experience lead persona: loyalty/sales data only, framed around customer behavior (walk-in vs loyalty mix, repeat visits) rather than Marketing''s engagement framing or Ops'' store-performance framing.';

CREATE USER IF NOT EXISTS NERO_CX_USER
  TYPE = SERVICE
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4ltEFQ1I5ZOZp3zL0MZeZtdtgF8eEMYY0o6SzWDJsD4h9ahiu3unO28Kh5+SR5fwZgcGeMogMGm8t2LLWbf/ST6lRmAIZHKmDp/sarp9CH48wgYZV6mpatz1J2wyofLjIs7iEtIZdbWiAh9CFpB8iy+IjDTJ8fPK7OfZ/K0FXvSiMr4+O2M4Cnm3ZtGwh9/1J+xcsZHfci8gmTbUmtlt98d7n6jyo+poSM3l/2XRukjcOuxL1KBoqEWAfRTMXcmJI4HpWxU+95jVhais80+k6MfRQG3/w0jY8TykkW9GULkZpxIhORsIUewLCeTLK0s/KHVorvCUy3dxEhm6duXsOwIDAQAB'
  DEFAULT_ROLE = NERO_CX_ROLE
  DEFAULT_WAREHOUSE = NERO_BI_WH
  COMMENT = 'Service identity owning the NERO_CX persona chatbot (leader_chatbots_app/).';

GRANT ROLE NERO_CX_ROLE TO USER NERO_CX_USER;

GRANT USAGE ON WAREHOUSE NERO_BI_WH TO ROLE NERO_CX_ROLE;
GRANT USAGE ON DATABASE NERO_GOVERNANCE TO ROLE NERO_CX_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.CORTEX_TOOLS TO ROLE NERO_CX_ROLE;
GRANT USAGE ON INTEGRATION NERO_PYPI_ACCESS_INTEGRATION TO ROLE NERO_CX_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_CX_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_CX_ROLE;


GRANT USAGE ON DATABASE NERO_DB TO ROLE NERO_CX_ROLE;
GRANT USAGE ON SCHEMA NERO_DB.NERO_LOYALTY TO ROLE NERO_CX_ROLE;
GRANT REFERENCES ON SEMANTIC VIEW NERO_DB.NERO_LOYALTY.LOYALTY_SEMANTIC_VIEW TO ROLE NERO_CX_ROLE;
GRANT USAGE ON SCHEMA NERO_DB."01_SILVER" TO ROLE NERO_CX_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA NERO_DB."01_SILVER" TO ROLE NERO_CX_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NERO_DB."01_SILVER" TO ROLE NERO_CX_ROLE;

-- ================= NERO_CDO_ROLE =================
CREATE ROLE IF NOT EXISTS NERO_CDO_ROLE
  COMMENT = 'Chief Data Officer / Data & Analytics lead persona: loyalty data AND platform cost -- data-platform-health framing, distinct from Finance''s P&L framing despite the same tool combination.';

CREATE USER IF NOT EXISTS NERO_CDO_USER
  TYPE = SERVICE
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuLBwesshmaS2Qu4WDI/7F8v+J/Qexsevwh0KDlNl8n51jzTyc7LWUORmvfaPQdUntY93Qntygig1ScYMf4TPzwlFauugCXUP+JRF92d69n2zUicF3ikVyeCUGjvKi3DfTbBjwB3KysAq6we2Up1WMu2nM/ydLanmsH6joaJph5ZFDuV/ieyw5MwCY2bQ5ptBeKy0zGGhY4HmGPsZFOGuI2dV/gyZpj9kND3aMiRXgYmVOvViCkYhK3uF8sod339TVj57EeAHP0uetosjO7UI/9aYvY1mOEf01AbgMagERt/rCY7DzMNvvNQ4Y6FQBOnUU2kV6pNTlzP/SD9uqXD5wwIDAQAB'
  DEFAULT_ROLE = NERO_CDO_ROLE
  DEFAULT_WAREHOUSE = NERO_BI_WH
  COMMENT = 'Service identity owning the NERO_CDO persona chatbot (leader_chatbots_app/).';

GRANT ROLE NERO_CDO_ROLE TO USER NERO_CDO_USER;

GRANT USAGE ON WAREHOUSE NERO_BI_WH TO ROLE NERO_CDO_ROLE;
GRANT USAGE ON DATABASE NERO_GOVERNANCE TO ROLE NERO_CDO_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.CORTEX_TOOLS TO ROLE NERO_CDO_ROLE;
GRANT USAGE ON INTEGRATION NERO_PYPI_ACCESS_INTEGRATION TO ROLE NERO_CDO_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_CDO_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_CDO_ROLE;


GRANT USAGE ON DATABASE NERO_DB TO ROLE NERO_CDO_ROLE;
GRANT USAGE ON SCHEMA NERO_DB.NERO_LOYALTY TO ROLE NERO_CDO_ROLE;
GRANT REFERENCES ON SEMANTIC VIEW NERO_DB.NERO_LOYALTY.LOYALTY_SEMANTIC_VIEW TO ROLE NERO_CDO_ROLE;
GRANT USAGE ON SCHEMA NERO_DB."01_SILVER" TO ROLE NERO_CDO_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA NERO_DB."01_SILVER" TO ROLE NERO_CDO_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NERO_DB."01_SILVER" TO ROLE NERO_CDO_ROLE;


GRANT USAGE ON SCHEMA NERO_GOVERNANCE.COST TO ROLE NERO_CDO_ROLE;
GRANT SELECT ON TABLE NERO_GOVERNANCE.COST.WAREHOUSE_BUDGET TO ROLE NERO_CDO_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA NERO_GOVERNANCE.COST TO ROLE NERO_CDO_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA NERO_GOVERNANCE.COST TO ROLE NERO_CDO_ROLE;
GRANT REFERENCES ON SEMANTIC VIEW NERO_GOVERNANCE.CORTEX_TOOLS.GOVERNANCE_SEMANTIC_VIEW TO ROLE NERO_CDO_ROLE;

-- ================= NERO_AUDIT_ROLE =================
CREATE ROLE IF NOT EXISTS NERO_AUDIT_ROLE
  COMMENT = 'Internal Audit / Compliance lead persona: security/Trust Center findings only -- audit/compliance framing, distinct from the Security lead''s remediation framing despite the same tool.';

CREATE USER IF NOT EXISTS NERO_AUDIT_USER
  TYPE = SERVICE
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq3BrinX6A2hcCu2ZN+ZTuwMzyNsLsrSkWfwdhoK7wAtNqnagBo+anCjcbxWMzB/P66WwSJlaA9lk3HVnay5Z1MVbU83/H6DKdgcNih02NyizGo35I59sWl2Bd6+TY7wkNd9jQWzM1v0GIuvs4uWbLTHJpqboNUoAKVWwvFePmwoFsGtXH5fCnicw753yiOzGVtLnSIbljWmVQHTQAt7XCiIqkvv5A3L2Ok/GiPuvyRRs3kpUBr+PaGAMNXAMLQGk7qMJ+jBqC10KQkqh8tp5GezcNtdglHMKoVlG6VjUkZbydh55GuSKSKgecBV/D1e9wVXo7tyTfxjUUBXRabKnJQIDAQAB'
  DEFAULT_ROLE = NERO_AUDIT_ROLE
  DEFAULT_WAREHOUSE = NERO_BI_WH
  COMMENT = 'Service identity owning the NERO_AUDIT persona chatbot (leader_chatbots_app/).';

GRANT ROLE NERO_AUDIT_ROLE TO USER NERO_AUDIT_USER;

GRANT USAGE ON WAREHOUSE NERO_BI_WH TO ROLE NERO_AUDIT_ROLE;
GRANT USAGE ON DATABASE NERO_GOVERNANCE TO ROLE NERO_AUDIT_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.CORTEX_TOOLS TO ROLE NERO_AUDIT_ROLE;
GRANT USAGE ON INTEGRATION NERO_PYPI_ACCESS_INTEGRATION TO ROLE NERO_AUDIT_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_AUDIT_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_AUDIT_ROLE;


GRANT USAGE ON SCHEMA NERO_GOVERNANCE.SECURITY TO ROLE NERO_AUDIT_ROLE;
GRANT USAGE ON CORTEX SEARCH SERVICE NERO_GOVERNANCE.SECURITY.FINDINGS_SEARCH_SVC TO ROLE NERO_AUDIT_ROLE;
GRANT SELECT ON TABLE NERO_GOVERNANCE.SECURITY.FINDINGS_DOCS TO ROLE NERO_AUDIT_ROLE;

-- ================= NERO_REGIONAL_ROLE =================
CREATE ROLE IF NOT EXISTS NERO_REGIONAL_ROLE
  COMMENT = 'Regional Director persona: store/region performance AND security findings -- combines loyalty data with security awareness, for a leader responsible for physical store regions.';

CREATE USER IF NOT EXISTS NERO_REGIONAL_USER
  TYPE = SERVICE
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo0lIqoD8H9ggyGn7Atg/CVnniVLIwL/pobd7WpRdJiYs/Ff4ymK2To/p2KITRITt2OfJl8LPt7lbS8OJt16U50aBMgpZIK+w541ztMvdfuZ4McJ901+13AeClc16BmbNqg/e2sP50E9FKfzm1uQ7lQdZseBvXoa7UrBrmpv3PahcomNbhuZQO8N4y9QWGZzFvuS5zWfXA3t10zEjt5UfrwFn7nY2KcIQNfSP1iXkDoEc0ji5VY2eI62mRqySZRxd9EA+N34dCgUlW5QM+UbICY/ABCD7Wf/MAWGcR4NboXogfDERDOwXJl/qekjJ7wdT9DOC8vUTbxfiVfvDew5Q2wIDAQAB'
  DEFAULT_ROLE = NERO_REGIONAL_ROLE
  DEFAULT_WAREHOUSE = NERO_BI_WH
  COMMENT = 'Service identity owning the NERO_REGIONAL persona chatbot (leader_chatbots_app/).';

GRANT ROLE NERO_REGIONAL_ROLE TO USER NERO_REGIONAL_USER;

GRANT USAGE ON WAREHOUSE NERO_BI_WH TO ROLE NERO_REGIONAL_ROLE;
GRANT USAGE ON DATABASE NERO_GOVERNANCE TO ROLE NERO_REGIONAL_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.CORTEX_TOOLS TO ROLE NERO_REGIONAL_ROLE;
GRANT USAGE ON INTEGRATION NERO_PYPI_ACCESS_INTEGRATION TO ROLE NERO_REGIONAL_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_REGIONAL_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_REGIONAL_ROLE;


GRANT USAGE ON DATABASE NERO_DB TO ROLE NERO_REGIONAL_ROLE;
GRANT USAGE ON SCHEMA NERO_DB.NERO_LOYALTY TO ROLE NERO_REGIONAL_ROLE;
GRANT REFERENCES ON SEMANTIC VIEW NERO_DB.NERO_LOYALTY.LOYALTY_SEMANTIC_VIEW TO ROLE NERO_REGIONAL_ROLE;
GRANT USAGE ON SCHEMA NERO_DB."01_SILVER" TO ROLE NERO_REGIONAL_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA NERO_DB."01_SILVER" TO ROLE NERO_REGIONAL_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NERO_DB."01_SILVER" TO ROLE NERO_REGIONAL_ROLE;


GRANT USAGE ON SCHEMA NERO_GOVERNANCE.SECURITY TO ROLE NERO_REGIONAL_ROLE;
GRANT USAGE ON CORTEX SEARCH SERVICE NERO_GOVERNANCE.SECURITY.FINDINGS_SEARCH_SVC TO ROLE NERO_REGIONAL_ROLE;
GRANT SELECT ON TABLE NERO_GOVERNANCE.SECURITY.FINDINGS_DOCS TO ROLE NERO_REGIONAL_ROLE;
