-- =============================================================================
-- Curated read-only surface for the Power BI platform control dashboard.
--
-- Keeps ACCOUNT_USAGE, Trust Center, control-plane JSON and application-layer
-- tables behind owner-rights views. NERO_POWERBI_ROLE receives SELECT only on
-- this schema; it does not receive direct access to the monitored sources.
--
-- Apply with:
--   snow sql -c snowflake_ai_dev_kit -f account_setup/powerbi_governance_reporting.sql
-- =============================================================================

USE ROLE ACCOUNTADMIN;

CREATE SCHEMA IF NOT EXISTS NERO_GOVERNANCE.REPORTING
  COMMENT = 'Curated operational metrics for Power BI cost, governance and pipeline-health reporting.';

CREATE OR REPLACE VIEW NERO_GOVERNANCE.REPORTING.COST_BUDGET_STATUS AS
SELECT
    WAREHOUSE_NAME,
    WORKLOAD,
    RESOURCE_MONITOR,
    CREDIT_QUOTA,
    CREDITS_USED_MTD,
    GREATEST(CREDIT_QUOTA - CREDITS_USED_MTD, 0) AS CREDITS_REMAINING,
    PCT_OF_BUDGET_USED,
    CASE
        WHEN PCT_OF_BUDGET_USED >= 100 THEN 'Critical'
        WHEN PCT_OF_BUDGET_USED >= 80 THEN 'Warning'
        ELSE 'Healthy'
    END AS BUDGET_STATUS
FROM NERO_GOVERNANCE.COST.BUDGET_VS_ACTUAL_MONTH_TO_DATE;

COMMENT ON VIEW NERO_GOVERNANCE.REPORTING.COST_BUDGET_STATUS IS
  'Current warehouse budget consumption with consistent Healthy/Warning/Critical thresholds.';

CREATE OR REPLACE VIEW NERO_GOVERNANCE.REPORTING.COST_DAILY AS
SELECT
    WAREHOUSE_NAME,
    USAGE_DATE::DATE AS USAGE_DATE,
    CREDITS_USED,
    CREDITS_USED_COMPUTE,
    CREDITS_USED_CLOUD_SERVICES
FROM NERO_GOVERNANCE.COST.WAREHOUSE_CREDITS_DAILY;

CREATE OR REPLACE VIEW NERO_GOVERNANCE.REPORTING.COST_BY_USER_DAILY AS
SELECT
    WAREHOUSE_NAME,
    USER_NAME,
    USAGE_DATE::DATE AS USAGE_DATE,
    QUERY_COUNT,
    CREDITS_ATTRIBUTED,
    CREDITS_QUERY_ACCELERATION
FROM NERO_GOVERNANCE.COST.WAREHOUSE_USER_CREDITS_DAILY;

CREATE OR REPLACE VIEW NERO_GOVERNANCE.REPORTING.SECURITY_FINDINGS AS
SELECT
    SCANNER_NAME,
    SEVERITY,
    CASE SEVERITY
        WHEN 'CRITICAL' THEN 1
        WHEN 'HIGH' THEN 2
        WHEN 'MEDIUM' THEN 3
        WHEN 'LOW' THEN 4
        ELSE 5
    END AS SEVERITY_SORT,
    STATE,
    TOTAL_AT_RISK_COUNT,
    RISK_DESCRIPTION,
    SUGGESTED_ACTION,
    CREATED_ON::DATE AS CREATED_DATE,
    STATE_LAST_MODIFIED_ON::DATE AS STATE_LAST_MODIFIED_DATE
FROM NERO_GOVERNANCE.SECURITY.OPEN_FINDINGS;

CREATE OR REPLACE VIEW NERO_GOVERNANCE.REPORTING.LOGIN_ACTIVITY_DAILY AS
SELECT
    LOGIN_DATE::DATE AS LOGIN_DATE,
    SUCCESS_COUNT,
    FAILED_COUNT
FROM NERO_GOVERNANCE.SECURITY.LOGIN_ACTIVITY_DAILY;

CREATE OR REPLACE VIEW NERO_GOVERNANCE.REPORTING.ACCOUNTADMIN_HOLDERS AS
SELECT
    USER_NAME,
    GRANTED_ROLE,
    GRANTED_BY,
    CREATED_ON::DATE AS GRANTED_DATE
FROM NERO_GOVERNANCE.SECURITY.ACCOUNTADMIN_HOLDERS;

-- Batches no longer carry a pass/fail status of their own -- PROCESS_BATCH's
-- batch-level gating (STATUS, DETAILS violation JSON) was retired in favour
-- of dbt's continuous SQL filtering (see NERO_DB."02_CONTROL".CONTRACT_REJECTIONS
-- for the dataset-level rejection rate that replaces it). This view is now
-- just the landing log: what landed, when, from which source.
CREATE OR REPLACE VIEW NERO_GOVERNANCE.REPORTING.PIPELINE_BATCH_RUNS AS
SELECT
    BATCH_ID,
    SOURCE_SYSTEM,
    DATASETS,
    CAPTURED_AT::DATE AS RUN_DATE,
    CAPTURED_AT
FROM NERO_DB."00_STAGING".STAGING_BATCH_MANIFESTS;

COMMENT ON VIEW NERO_GOVERNANCE.REPORTING.PIPELINE_BATCH_RUNS IS
  'Batches landed into staging -- source, datasets, and when. Per-batch pass/fail no longer applies (see CONTRACT_REJECTIONS for the dataset-level rejection rate that replaced it).';

CREATE OR REPLACE VIEW NERO_GOVERNANCE.REPORTING.PIPELINE_TASK_RUNS AS
SELECT
    NAME AS TASK_NAME,
    STATE,
    SCHEDULED_TIME::DATE AS RUN_DATE,
    SCHEDULED_TIME,
    QUERY_START_TIME,
    COMPLETED_TIME,
    DATEDIFF('second', QUERY_START_TIME, COMPLETED_TIME) AS DURATION_SECONDS,
    ERROR_MESSAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
WHERE NAME IN ('SYNTHETIC_DAILY_INGEST_TASK', 'DBT_DAILY_REFRESH_TASK')
  AND SCHEDULED_TIME >= DATEADD('day', -90, CURRENT_TIMESTAMP());

COMMENT ON VIEW NERO_GOVERNANCE.REPORTING.PIPELINE_TASK_RUNS IS
  'Last 90 days of scheduled ingestion and dbt task outcomes from ACCOUNT_USAGE.';

-- Updated for the Staging/Bronze/Silver rename (see analytics/README.md):
-- Raw landing -> Staging, Validated -> Bronze (dbt-owned), Silver is views
-- (no row count of its own -- see the 00_SILVER views directly if needed),
-- Transformed -> Gold, unchanged.
CREATE OR REPLACE VIEW NERO_GOVERNANCE.REPORTING.PIPELINE_LAYER_VOLUMES AS
SELECT 'Raw landing' AS LAYER, 'STAGING_STORES' AS OBJECT_NAME,
       COUNT(*) AS ROW_COUNT, CURRENT_TIMESTAMP() AS SNAPSHOT_AT
FROM NERO_DB."00_STAGING".STAGING_STORES
UNION ALL
SELECT 'Raw landing', 'STAGING_LOYALTY_CUSTOMERS', COUNT(*), CURRENT_TIMESTAMP()
FROM NERO_DB."00_STAGING".STAGING_LOYALTY_CUSTOMERS
UNION ALL
SELECT 'Raw landing', 'STAGING_TRANSACTIONS', COUNT(*), CURRENT_TIMESTAMP()
FROM NERO_DB."00_STAGING".STAGING_TRANSACTIONS
UNION ALL
SELECT 'Raw landing', 'STAGING_LOYALTY_EVENTS', COUNT(*), CURRENT_TIMESTAMP()
FROM NERO_DB."00_STAGING".STAGING_LOYALTY_EVENTS
UNION ALL
SELECT 'Bronze (contract-filtered)', 'BRONZE_STORES', COUNT(*), CURRENT_TIMESTAMP()
FROM NERO_DB."01_BRONZE".BRONZE_STORES
UNION ALL
SELECT 'Bronze (contract-filtered)', 'BRONZE_LOYALTY_CUSTOMERS', COUNT(*), CURRENT_TIMESTAMP()
FROM NERO_DB."01_BRONZE".BRONZE_LOYALTY_CUSTOMERS
UNION ALL
SELECT 'Bronze (contract-filtered)', 'BRONZE_TRANSACTIONS', COUNT(*), CURRENT_TIMESTAMP()
FROM NERO_DB."01_BRONZE".BRONZE_TRANSACTIONS
UNION ALL
SELECT 'Bronze (contract-filtered)', 'BRONZE_LOYALTY_EVENTS', COUNT(*), CURRENT_TIMESTAMP()
FROM NERO_DB."01_BRONZE".BRONZE_LOYALTY_EVENTS
UNION ALL
SELECT 'Transformed (Gold)', 'DIM_STORE', COUNT(*), CURRENT_TIMESTAMP()
FROM NERO_ANALYTICS."02_GOLD".DIM_STORE
UNION ALL
SELECT 'Transformed (Gold)', 'DIM_CUSTOMER_SCD', COUNT(*), CURRENT_TIMESTAMP()
FROM NERO_ANALYTICS."02_GOLD".DIM_CUSTOMER_SCD
UNION ALL
SELECT 'Transformed (Gold)', 'FACT_SALES_TRANSACTION', COUNT(*), CURRENT_TIMESTAMP()
FROM NERO_ANALYTICS."02_GOLD".FACT_SALES_TRANSACTION
UNION ALL
SELECT 'Transformed (Gold)', 'FACT_LOYALTY_EVENT', COUNT(*), CURRENT_TIMESTAMP()
FROM NERO_ANALYTICS."02_GOLD".FACT_LOYALTY_EVENT;

-- The release-pointer concept was retired with PROCESS_BATCH (no more
-- single atomic "current release" gate -- dbt publishes continuously).
-- Rebuilt as "what's current" in the new model: latest batch landed and
-- latest dbt run, the two events that actually move data forward now.
CREATE OR REPLACE VIEW NERO_GOVERNANCE.REPORTING.CURRENT_RELEASE AS
SELECT
    (SELECT BATCH_ID FROM NERO_DB."00_STAGING".STAGING_BATCH_MANIFESTS
       ORDER BY CAPTURED_AT DESC LIMIT 1)                                  AS LATEST_BATCH_ID,
    (SELECT MAX(CAPTURED_AT) FROM NERO_DB."00_STAGING".STAGING_BATCH_MANIFESTS) AS LATEST_BATCH_LANDED_AT,
    (SELECT MAX(RUN_STARTED_AT) FROM NERO_ANALYTICS."05_QUALITY".DBT_TEST_RESULTS) AS LATEST_DBT_RUN_AT;

COMMENT ON VIEW NERO_GOVERNANCE.REPORTING.CURRENT_RELEASE IS
  'What''s current in the continuous (non-batch-gated) pipeline: latest batch landed and latest dbt run.';

CREATE OR REPLACE VIEW NERO_GOVERNANCE.REPORTING.CONTRACT_REJECTIONS AS
SELECT * FROM NERO_DB."02_CONTROL".CONTRACT_REJECTIONS;

COMMENT ON VIEW NERO_GOVERNANCE.REPORTING.CONTRACT_REJECTIONS IS
  'Per-dataset contract-rejection rate: staged keys vs. published-to-bronze keys.';

CREATE OR REPLACE VIEW NERO_GOVERNANCE.REPORTING.DATASET_FRESHNESS AS
SELECT * FROM NERO_DB."04_METADATA".DATASET_FRESHNESS;

COMMENT ON VIEW NERO_GOVERNANCE.REPORTING.DATASET_FRESHNESS IS
  'Per-dataset landing freshness: latest row staged vs. latest row published to bronze.';

GRANT USAGE ON DATABASE NERO_DB TO ROLE NERO_POWERBI_ROLE;
GRANT USAGE ON SCHEMA NERO_DB."02_CONTROL" TO ROLE NERO_POWERBI_ROLE;
GRANT SELECT ON VIEW NERO_DB."02_CONTROL".CONTRACT_REJECTIONS TO ROLE NERO_POWERBI_ROLE;
GRANT USAGE ON SCHEMA NERO_DB."04_METADATA" TO ROLE NERO_POWERBI_ROLE;
GRANT SELECT ON VIEW NERO_DB."04_METADATA".DATASET_FRESHNESS TO ROLE NERO_POWERBI_ROLE;

GRANT USAGE ON DATABASE NERO_GOVERNANCE TO ROLE NERO_POWERBI_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.REPORTING TO ROLE NERO_POWERBI_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA NERO_GOVERNANCE.REPORTING TO ROLE NERO_POWERBI_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA NERO_GOVERNANCE.REPORTING TO ROLE NERO_POWERBI_ROLE;

SELECT 'powerbi_governance_reporting applied' AS STATUS;
