-- =============================================================================
-- Streamlit apps reorg: split the flat NERO_GOVERNANCE.APPS schema into three
-- purpose-named schemas, and rename what's left of APPS to CORTEX_TOOLS.
--
-- Before this: 17 Streamlit apps (dashboards, chatbots, leader personas) all
-- lived in one NERO_GOVERNANCE.APPS schema alongside the shared Cortex Agent,
-- MCP server and semantic view -- confusing both in Snowflake (SHOW STREAMLITS
-- returned everything mixed together) and in the repo (6 similarly-named
-- folders: governance_app/ vs governance_chatbot_app/ vs
-- chatbot_governance_app/). This file is the Snowflake-side half of that
-- reorg; the repo-side half moved every app under streamlit_apps/{dashboards,
-- chatbots,leaders}/ with shared code in streamlit_apps/shared/ (see
-- streamlit_apps/snowflake.yml).
--
-- New layout:
--   NERO_GOVERNANCE.APPS_DASHBOARDS -- business/platform dashboards
--   NERO_GOVERNANCE.APPS_CHATBOTS   -- the 2 core chatbots + their 2 usage
--                                      report dashboards + shared chat
--                                      history tables (CHAT_CONVERSATIONS,
--                                      CHAT_MESSAGES)
--   NERO_GOVERNANCE.APPS_LEADERS    -- the 10 department-leader personas
--   NERO_GOVERNANCE.CORTEX_TOOLS    -- (renamed from APPS) shared Cortex
--                                      infra only: GOVERNANCE_SEMANTIC_VIEW,
--                                      NERO_PLATFORM_AGENT,
--                                      NERO_PLATFORM_MCP_SERVER,
--                                      PYPI_NETWORK_RULE
--
-- Idempotent: safe to re-run. Apply with:
--   snow sql -f account_setup/streamlit_apps_reorg.sql
-- (uses plain single-statement GRANTs throughout, so the CLI's Jinja
-- templating issue with multi-statement/dollar-quoted files doesn't apply
-- here.)
-- =============================================================================

USE ROLE ACCOUNTADMIN;

CREATE SCHEMA IF NOT EXISTS NERO_GOVERNANCE.APPS_DASHBOARDS
  COMMENT = 'Business/platform Streamlit dashboards (loyalty trading pulse, cost & security governance reports).';

CREATE SCHEMA IF NOT EXISTS NERO_GOVERNANCE.APPS_CHATBOTS
  COMMENT = 'Cortex Agent-powered chatbots (Nero Assistant, Nero Governance Assistant) plus their usage-report dashboards, and the shared chat history tables both write to.';

CREATE SCHEMA IF NOT EXISTS NERO_GOVERNANCE.APPS_LEADERS
  COMMENT = 'Per-department-leader chatbot personas (marketing, ops, finance, security, platform, CEO, CX, CDO, audit, regional).';

-- APPS was the original catch-all schema. Once every Streamlit app moved out
-- to the three schemas above, all that remained in it was shared Cortex
-- infrastructure (agent, MCP server, semantic view, PyPI network rule) --
-- not "apps" -- so it's renamed rather than left with a misleading name.
-- ALTER SCHEMA ... RENAME preserves object identity and every existing grant
-- on the schema and everything inside it (verified via SHOW GRANTS before/
-- after), so this is safe to run against a live environment.
ALTER SCHEMA NERO_GOVERNANCE.APPS RENAME TO CORTEX_TOOLS;

-- Chat history tables moved from APPS to APPS_CHATBOTS (both core chatbots
-- write here; RENAME preserves rows and existing grants).
ALTER TABLE NERO_GOVERNANCE.CORTEX_TOOLS.CHAT_CONVERSATIONS
  RENAME TO NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS;
ALTER TABLE NERO_GOVERNANCE.CORTEX_TOOLS.CHAT_MESSAGES
  RENAME TO NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES;

-- ============================ SCHEMA-LEVEL GRANTS =============================
-- Every role that used to get USAGE/CREATE STREAMLIT on the old flat APPS
-- schema now gets USAGE + CREATE STREAMLIT scoped to just the schema(s)
-- holding the apps it actually owns (confirmed live via
-- SHOW STREAMLITS IN SCHEMA ... across all three new schemas):
--   NERO_BI_ROLE         -> APPS_DASHBOARDS (LOYALTY_ENGAGEMENT_SALES),
--                           APPS_CHATBOTS (NERO_ASSISTANT)
--   NERO_GOVERNANCE_ROLE -> APPS_DASHBOARDS (COST_GOVERNANCE_REPORT,
--                           SECURITY_GOVERNANCE_REPORT),
--                           APPS_CHATBOTS (CHATBOT_COST_GOVERNANCE_REPORT,
--                           CHATBOT_SECURITY_GOVERNANCE_REPORT,
--                           NERO_GOVERNANCE_ASSISTANT)
--   NERO_CI_ROLE         -> all three (CI redeploys every app)
--   10 leader roles      -> APPS_LEADERS only (one persona app each)
-- USAGE on CORTEX_TOOLS itself (for the semantic view / agent / MCP server)
-- is unaffected by this file -- it's the same grant every role already had
-- on APPS pre-rename, which RENAME preserved; see chat_history_tables.sql,
-- leader_personas_stack*.sql, governance_chatbot_stack.sql, service_users.sql,
-- copilot_mcp_access.sql for those (now CORTEX_TOOLS-qualified) grants.

GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_DASHBOARDS TO ROLE NERO_BI_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_DASHBOARDS TO ROLE NERO_BI_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_BI_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_BI_ROLE;

GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_DASHBOARDS TO ROLE NERO_GOVERNANCE_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_DASHBOARDS TO ROLE NERO_GOVERNANCE_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_GOVERNANCE_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_GOVERNANCE_ROLE;

GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_DASHBOARDS TO ROLE NERO_CI_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_DASHBOARDS TO ROLE NERO_CI_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_CI_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_CI_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_CI_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_CI_ROLE;

GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_MARKETING_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_MARKETING_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_OPS_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_OPS_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_FINANCE_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_FINANCE_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_SECURITY_LEAD_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_SECURITY_LEAD_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_CEO_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_CEO_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_CX_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_CX_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_CDO_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_CDO_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_AUDIT_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_AUDIT_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_REGIONAL_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA NERO_GOVERNANCE.APPS_LEADERS TO ROLE NERO_REGIONAL_ROLE;

-- All 10 leader personas share the same shared/chat_store.py against the
-- chat history tables, which live in APPS_CHATBOTS (not APPS_LEADERS) --
-- so each leader role also needs USAGE on APPS_CHATBOTS itself, not just
-- object-level SELECT/INSERT/UPDATE on the two tables below (a table grant
-- without USAGE on its containing schema is unusable). This was missed on
-- the first pass here and broke every leader persona's chat history at
-- runtime with "Schema 'NERO_GOVERNANCE.APPS_CHATBOTS' does not exist or
-- not authorized" until caught and fixed live.
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_MARKETING_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_OPS_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_FINANCE_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_SECURITY_LEAD_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_CEO_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_CX_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_CDO_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_AUDIT_ROLE;
GRANT USAGE ON SCHEMA NERO_GOVERNANCE.APPS_CHATBOTS TO ROLE NERO_REGIONAL_ROLE;

-- ============================ CHAT HISTORY TABLE GRANTS ========================
-- Same SELECT/INSERT/UPDATE grants the tables had under APPS, reissued
-- against their new APPS_CHATBOTS home for every role whose app writes to
-- them (both core chatbots + all 10 leader personas, which share the same
-- chat_store.py against this one pair of tables).

GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_MARKETING_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_MARKETING_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_OPS_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_OPS_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_FINANCE_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_FINANCE_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_SECURITY_LEAD_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_SECURITY_LEAD_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_PLATFORM_LEAD_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_CEO_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_CEO_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_CX_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_CX_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_CDO_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_CDO_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_AUDIT_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_AUDIT_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_CONVERSATIONS TO ROLE NERO_REGIONAL_ROLE;
GRANT SELECT, INSERT ON TABLE NERO_GOVERNANCE.APPS_CHATBOTS.CHAT_MESSAGES TO ROLE NERO_REGIONAL_ROLE;

-- ============================ INCIDENTAL OWNERSHIP FIX ==========================
-- Five apps had been stuck on ACCOUNTADMIN ownership since earlier phases
-- (GRANT OWNERSHIP ON STREAMLIT isn't supported by Snowflake -- the only way
-- to assign a specific owning role is to deploy via a `snow` CLI connection
-- already authenticated as that role). Redeploying all 17 apps as part of
-- this reorg fixed that as a side effect:
--   LOYALTY_ENGAGEMENT_SALES, CHATBOT_COST_GOVERNANCE_REPORT,
--   CHATBOT_SECURITY_GOVERNANCE_REPORT -> now NERO_BI_ROLE / NERO_GOVERNANCE_ROLE
--   COST_GOVERNANCE_REPORT, SECURITY_GOVERNANCE_REPORT -> now NERO_GOVERNANCE_ROLE
-- No further grants needed here -- this note just documents the change for
-- anyone diffing SHOW GRANTS output against an earlier snapshot.
