-- =============================================================================
-- RETIRED. DBT_DAILY_REFRESH_TASK is now created by
-- account_setup/daily_pipeline_orchestration.sql, as the leaf of a real
-- task DAG alongside SYNTHETIC_DAILY_INGEST_TASK and
-- GOOGLE_SHEETS_INGEST_TASK, rather than independently cron-scheduled 15
-- minutes after the ingestion tasks and hoping that was enough headroom.
--
-- This file previously argued against an AFTER dependency on cross-owner/
-- cross-schema grounds ("fragility"). That undersold the actual
-- constraint: Snowflake requires every task in one DAG to share both an
-- owner role and a schema, so a DAG spanning
-- NERO_DB."02_CONTROL" (ACCOUNTADMIN) and NERO_ANALYTICS.DBT_PROJECT
-- (NERO_DBT_ROLE) was never possible, not just fragile. See
-- account_setup/daily_pipeline_orchestration.sql for the fix (consolidating
-- all three tasks under NERO_DBT_ROLE in NERO_ANALYTICS.DBT_PROJECT) and
-- the reasoning in full.
-- =============================================================================
