-- MANUAL STEP — not run by CI, not DCM-managed.
-- DCM's DEFINE MASKING POLICY only creates the policy; attaching it to a
-- column isn't yet a supported DCM primitive. Review and run this by hand
-- (or via a reviewed post_deploy.sql) after the policy + table are deployed.

ALTER TABLE NERO_DB.NERO_LOYALTY.VALIDATED_LOYALTY_CUSTOMERS MODIFY COLUMN CUSTOMER_ID SET MASKING POLICY NERO_DB.NERO_LOYALTY.MASK_IDENTIFIER_INTEGER;
ALTER TABLE NERO_DB.NERO_LOYALTY.VALIDATED_TRANSACTIONS MODIFY COLUMN CUSTOMER_ID SET MASKING POLICY NERO_DB.NERO_LOYALTY.MASK_IDENTIFIER_INTEGER;
ALTER TABLE NERO_DB.NERO_LOYALTY.VALIDATED_LOYALTY_EVENTS MODIFY COLUMN CUSTOMER_ID SET MASKING POLICY NERO_DB.NERO_LOYALTY.MASK_IDENTIFIER_INTEGER;
