"""Single-table PDF/Excel export for chat results.

Lighter than governance_app/report_common.py (no multi-section report
scaffolding) -- this exports exactly one query result: the table the
agent just returned, plus the question that produced it.
"""
import io
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

INK = colors.HexColor("#1c2b3a")
INK_SECONDARY = colors.HexColor("#4c5c6b")
MUTED = colors.HexColor("#8a97a3")
RULE = colors.HexColor("#d7dde2")
ACCENT = colors.HexColor("#3d5a73")
HEADER_BG = colors.HexColor("#eaeff3")

_styles = getSampleStyleSheet()
TITLE_STYLE = ParagraphStyle("Title", parent=_styles["Title"], fontName="Helvetica-Bold", fontSize=16, textColor=INK)
META_STYLE = ParagraphStyle("Meta", parent=_styles["Normal"], fontName="Helvetica", fontSize=9.5, textColor=INK_SECONDARY, spaceAfter=10)
CAPTION_STYLE = ParagraphStyle("Caption", parent=_styles["Normal"], fontName="Helvetica-Oblique", fontSize=8, textColor=MUTED, spaceBefore=10)


def build_table_pdf(question: str, columns: list[str], rows: list[list]) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=landscape(A4),
        leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm, bottomMargin=16 * mm,
        title="Nero Assistant result",
    )
    data = [columns] + [[str(c) if c is not None else "" for c in r] for r in rows]
    tbl = Table(data, repeatRows=1)
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), HEADER_BG),
        ("TEXTCOLOR", (0, 0), (-1, 0), INK),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("TEXTCOLOR", (0, 1), (-1, -1), INK),
        ("GRID", (0, 0), (-1, -1), 0.5, RULE),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story = [
        Paragraph("Nero Governance Assistant — result export", TITLE_STYLE),
        Paragraph(f"Q: {question}", META_STYLE),
        Paragraph(f"Generated {datetime.now(timezone.utc).strftime('%d %b %Y %H:%M UTC')}", META_STYLE),
        Spacer(1, 6),
        tbl,
        Paragraph("Generated by Nero Assistant — verify before using in a formal report.", CAPTION_STYLE),
    ]
    doc.build(story)
    return buf.getvalue()


def build_table_excel(question: str, columns: list[str], rows: list[list]) -> bytes:
    import pandas as pd

    df = pd.DataFrame(rows, columns=columns)
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="xlsxwriter") as writer:
        df.to_excel(writer, sheet_name="Result", startrow=3, index=False, header=False)
        wb = writer.book
        ws = writer.sheets["Result"]
        title_fmt = wb.add_format({"bold": True, "font_size": 13, "font_color": "#1C2B3A"})
        meta_fmt = wb.add_format({"italic": True, "font_size": 9, "font_color": "#8A97A3"})
        header_fmt = wb.add_format({"bold": True, "bg_color": "#EAEFF3", "border": 1, "border_color": "#D7DDE2", "font_color": "#1C2B3A"})
        ws.write(0, 0, "Nero Governance Assistant — result export", title_fmt)
        ws.write(1, 0, f"Q: {question}"[:250], meta_fmt)
        ws.write(2, 0, f"Generated {datetime.now(timezone.utc).strftime('%d %b %Y %H:%M UTC')}", meta_fmt)
        for i, col in enumerate(columns):
            ws.write(3, i, col, header_fmt)
            width = max(10, min(40, df[col].astype(str).str.len().max() if len(df) else 10, len(str(col)) + 2))
            ws.set_column(i, i, width)
        ws.freeze_panes(4, 0)
    return buf.getvalue()
