-- =============================================================================
-- Data Contract Ingestion Pattern — Control Plane, Work Table, Gate Task
-- Database: NERO_DB  Schema: NERO_LOYALTY
--
-- Everything about the pipeline that's hand-written and structural (not
-- generated from contracts/loyalty.yaml, and not dataset-specific): the
-- control tables (contract registry, audit trail, release pointer), the
-- frozen-batch work table, and the scheduled gate task.
--
-- RAW_ENVELOPES and VALIDATED_* tables are GENERATED by tools/build.py —
-- see contract_raw.sql and contract_validated_tables.sql.
-- =============================================================================

-- =========================== CONTROL TABLES =================================

DEFINE TABLE NERO_DB.NERO_LOYALTY.CONTROL_DATA_CONTRACTS (
    CONTRACT_ID    VARCHAR(200)   NOT NULL,
    VERSION        NUMBER         NOT NULL,
    CONTRACT_JSON  VARIANT        NOT NULL,
    CONTRACT_HASH  VARCHAR(64)    NOT NULL,
    LOADED_AT      TIMESTAMP_TZ   DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CONTRACT_ID, VERSION)
)
COMMENT = 'Reviewed data contract documents, keyed by contract_id+version. CONTRACT_HASH is the SHA-256 of the exact contract bytes, pinned by the stored procedures at deploy time.';

DEFINE TABLE NERO_DB.NERO_LOYALTY.CONTROL_RUN_AUDIT (
    BATCH_ID     VARCHAR(200)   NOT NULL,
    RUN_ID       VARCHAR(200)   NOT NULL,
    STATUS       VARCHAR(30)    NOT NULL,
    DETAILS      VARIANT,
    RECORDED_AT  TIMESTAMP_TZ   DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Audit trail of every PROCESS_BATCH invocation. STATUS one of: PUBLISHED, ALREADY_PUBLISHED, SUPERSEDED, REJECTED, INCOMPLETE, ERROR.';

DEFINE TABLE NERO_DB.NERO_LOYALTY.CONTROL_RELEASE_POINTER (
    POINTER_NAME       VARCHAR(50)   NOT NULL,
    CURRENT_BATCH_ID   VARCHAR(200),
    CURRENT_RELEASE_AT TIMESTAMP_TZ,
    UPDATED_AT         TIMESTAMP_TZ  DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (POINTER_NAME)
)
COMMENT = 'Compare-and-set pointer to the currently published batch. Reporting views join on this to expose only the approved release.';

-- ============================ WORK TABLE ====================================

DEFINE TABLE NERO_DB.NERO_LOYALTY.WORK_ENVELOPES (
    RUN_ID       VARCHAR(200)  NOT NULL,
    BATCH_ID     VARCHAR(200)  NOT NULL,
    DOC          VARIANT       NOT NULL,
    FROZEN_AT    TIMESTAMP_TZ  DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Frozen snapshot of one batch''s raw envelopes for a single PROCESS_BATCH run. Written by one INSERT...SELECT so all downstream checks read the same fixed set. Cleared after normal runs.';

-- ============================= GATE TASK ====================================
-- Suspended by default (DCM default) — resume explicitly once smoke tests
-- pass. Snowflake auto-suspends after 3 consecutive failures.

DEFINE TASK NERO_DB.NERO_LOYALTY.CONTRACT_GATE_TASK
    WAREHOUSE = 'COMPUTE_WH'
    SCHEDULE = '15 MINUTE'
    COMMENT = 'Calls RUN_PENDING to evaluate/publish outstanding manifested batches. Suspended until explicitly resumed post smoke-test.'
AS
    CALL NERO_DB.NERO_LOYALTY.RUN_PENDING();
